// GENERATED by scripts/generate-s57.mjs — DO NOT EDIT.
// Source: IHO S-57 Appendix A Object Catalogue (vendored GDAL CSVs).
// Regenerate with: npm run gen:s57

/** An S-57 attribute's value domain. `enum`/`list` map through ENUMS. */
export type AttributeType = "enum" | "list" | "float" | "int" | "string";

/** OBJL (object-class code) → acronym + official label. */
export const OBJECT_CLASSES: Record<number, { acronym: string; label: string }> =
  {
  "1": {
    "acronym": "ADMARE",
    "label": "Administration area (Named)"
  },
  "2": {
    "acronym": "AIRARE",
    "label": "Airport / airfield"
  },
  "3": {
    "acronym": "ACHBRT",
    "label": "Anchor berth"
  },
  "4": {
    "acronym": "ACHARE",
    "label": "Anchorage area"
  },
  "5": {
    "acronym": "BCNCAR",
    "label": "Beacon, cardinal"
  },
  "6": {
    "acronym": "BCNISD",
    "label": "Beacon, isolated danger"
  },
  "7": {
    "acronym": "BCNLAT",
    "label": "Beacon, lateral"
  },
  "8": {
    "acronym": "BCNSAW",
    "label": "Beacon, safe water"
  },
  "9": {
    "acronym": "BCNSPP",
    "label": "Beacon, special purpose/general"
  },
  "10": {
    "acronym": "BERTHS",
    "label": "Berth"
  },
  "11": {
    "acronym": "BRIDGE",
    "label": "Bridge"
  },
  "12": {
    "acronym": "BUISGL",
    "label": "Building, single"
  },
  "13": {
    "acronym": "BUAARE",
    "label": "Built-up area"
  },
  "14": {
    "acronym": "BOYCAR",
    "label": "Buoy, cardinal"
  },
  "15": {
    "acronym": "BOYINB",
    "label": "Buoy, installation"
  },
  "16": {
    "acronym": "BOYISD",
    "label": "Buoy, isolated danger"
  },
  "17": {
    "acronym": "BOYLAT",
    "label": "Buoy, lateral"
  },
  "18": {
    "acronym": "BOYSAW",
    "label": "Buoy, safe water"
  },
  "19": {
    "acronym": "BOYSPP",
    "label": "Buoy, special purpose/general"
  },
  "20": {
    "acronym": "CBLARE",
    "label": "Cable area"
  },
  "21": {
    "acronym": "CBLOHD",
    "label": "Cable, overhead"
  },
  "22": {
    "acronym": "CBLSUB",
    "label": "Cable, submarine"
  },
  "23": {
    "acronym": "CANALS",
    "label": "Canal"
  },
  "24": {
    "acronym": "CANBNK",
    "label": "Canal bank"
  },
  "25": {
    "acronym": "CTSARE",
    "label": "Cargo transshipment area"
  },
  "26": {
    "acronym": "CAUSWY",
    "label": "Causeway"
  },
  "27": {
    "acronym": "CTNARE",
    "label": "Caution area"
  },
  "28": {
    "acronym": "CHKPNT",
    "label": "Checkpoint"
  },
  "29": {
    "acronym": "CGUSTA",
    "label": "Coastguard station"
  },
  "30": {
    "acronym": "COALNE",
    "label": "Coastline"
  },
  "31": {
    "acronym": "CONZNE",
    "label": "Contiguous zone"
  },
  "32": {
    "acronym": "COSARE",
    "label": "Continental shelf area"
  },
  "33": {
    "acronym": "CTRPNT",
    "label": "Control point"
  },
  "34": {
    "acronym": "CONVYR",
    "label": "Conveyor"
  },
  "35": {
    "acronym": "CRANES",
    "label": "Crane"
  },
  "36": {
    "acronym": "CURENT",
    "label": "Current - non - gravitational"
  },
  "37": {
    "acronym": "CUSZNE",
    "label": "Custom zone"
  },
  "38": {
    "acronym": "DAMCON",
    "label": "Dam"
  },
  "39": {
    "acronym": "DAYMAR",
    "label": "Daymark"
  },
  "40": {
    "acronym": "DWRTCL",
    "label": "Deep water route centerline"
  },
  "41": {
    "acronym": "DWRTPT",
    "label": "Deep water route part"
  },
  "42": {
    "acronym": "DEPARE",
    "label": "Depth area"
  },
  "43": {
    "acronym": "DEPCNT",
    "label": "Depth contour"
  },
  "44": {
    "acronym": "DISMAR",
    "label": "Distance mark"
  },
  "45": {
    "acronym": "DOCARE",
    "label": "Dock area"
  },
  "46": {
    "acronym": "DRGARE",
    "label": "Dredged area"
  },
  "47": {
    "acronym": "DRYDOC",
    "label": "Dry dock"
  },
  "48": {
    "acronym": "DMPGRD",
    "label": "Dumping ground"
  },
  "49": {
    "acronym": "DYKCON",
    "label": "Dyke"
  },
  "50": {
    "acronym": "EXEZNE",
    "label": "Exclusive Economic Zone"
  },
  "51": {
    "acronym": "FAIRWY",
    "label": "Fairway"
  },
  "52": {
    "acronym": "FNCLNE",
    "label": "Fence/wall"
  },
  "53": {
    "acronym": "FERYRT",
    "label": "Ferry route"
  },
  "54": {
    "acronym": "FSHZNE",
    "label": "Fishery zone"
  },
  "55": {
    "acronym": "FSHFAC",
    "label": "Fishing facility"
  },
  "56": {
    "acronym": "FSHGRD",
    "label": "Fishing ground"
  },
  "57": {
    "acronym": "FLODOC",
    "label": "Floating dock"
  },
  "58": {
    "acronym": "FOGSIG",
    "label": "Fog signal"
  },
  "59": {
    "acronym": "FORSTC",
    "label": "Fortified structure"
  },
  "60": {
    "acronym": "FRPARE",
    "label": "Free port area"
  },
  "61": {
    "acronym": "GATCON",
    "label": "Gate"
  },
  "62": {
    "acronym": "GRIDRN",
    "label": "Gridiron"
  },
  "63": {
    "acronym": "HRBARE",
    "label": "Harbour area (administrative)"
  },
  "64": {
    "acronym": "HRBFAC",
    "label": "Harbour facility"
  },
  "65": {
    "acronym": "HULKES",
    "label": "Hulk"
  },
  "66": {
    "acronym": "ICEARE",
    "label": "Ice area"
  },
  "67": {
    "acronym": "ICNARE",
    "label": "Incineration area"
  },
  "68": {
    "acronym": "ISTZNE",
    "label": "Inshore traffic zone"
  },
  "69": {
    "acronym": "LAKARE",
    "label": "Lake"
  },
  "70": {
    "acronym": "LAKSHR",
    "label": "Lake shore"
  },
  "71": {
    "acronym": "LNDARE",
    "label": "Land area"
  },
  "72": {
    "acronym": "LNDELV",
    "label": "Land elevation"
  },
  "73": {
    "acronym": "LNDRGN",
    "label": "Land region"
  },
  "74": {
    "acronym": "LNDMRK",
    "label": "Landmark"
  },
  "75": {
    "acronym": "LIGHTS",
    "label": "Light"
  },
  "76": {
    "acronym": "LITFLT",
    "label": "Light float"
  },
  "77": {
    "acronym": "LITVES",
    "label": "Light vessel"
  },
  "78": {
    "acronym": "LOCMAG",
    "label": "Local magnetic anomaly"
  },
  "79": {
    "acronym": "LOKBSN",
    "label": "Lock basin"
  },
  "80": {
    "acronym": "LOGPON",
    "label": "Log pond"
  },
  "81": {
    "acronym": "MAGVAR",
    "label": "Magnetic variation"
  },
  "82": {
    "acronym": "MARCUL",
    "label": "Marine farm/culture"
  },
  "83": {
    "acronym": "MIPARE",
    "label": "Military practice area"
  },
  "84": {
    "acronym": "MORFAC",
    "label": "Mooring/warping facility"
  },
  "85": {
    "acronym": "NAVLNE",
    "label": "Navigation line"
  },
  "86": {
    "acronym": "OBSTRN",
    "label": "Obstruction"
  },
  "87": {
    "acronym": "OFSPLF",
    "label": "Offshore platform"
  },
  "88": {
    "acronym": "OSPARE",
    "label": "Offshore production area"
  },
  "89": {
    "acronym": "OILBAR",
    "label": "Oil barrier"
  },
  "90": {
    "acronym": "PILPNT",
    "label": "Pile"
  },
  "91": {
    "acronym": "PILBOP",
    "label": "Pilot boarding place"
  },
  "92": {
    "acronym": "PIPARE",
    "label": "Pipeline area"
  },
  "93": {
    "acronym": "PIPOHD",
    "label": "Pipeline, overhead"
  },
  "94": {
    "acronym": "PIPSOL",
    "label": "Pipeline, submarine/on land"
  },
  "95": {
    "acronym": "PONTON",
    "label": "Pontoon"
  },
  "96": {
    "acronym": "PRCARE",
    "label": "Precautionary area"
  },
  "97": {
    "acronym": "PRDARE",
    "label": "Production / storage area"
  },
  "98": {
    "acronym": "PYLONS",
    "label": "Pylon/bridge support"
  },
  "99": {
    "acronym": "RADLNE",
    "label": "Radar line"
  },
  "100": {
    "acronym": "RADRNG",
    "label": "Radar range"
  },
  "101": {
    "acronym": "RADRFL",
    "label": "Radar reflector"
  },
  "102": {
    "acronym": "RADSTA",
    "label": "Radar station"
  },
  "103": {
    "acronym": "RTPBCN",
    "label": "Radar transponder beacon"
  },
  "104": {
    "acronym": "RDOCAL",
    "label": "Radio calling-in point"
  },
  "105": {
    "acronym": "RDOSTA",
    "label": "Radio station"
  },
  "106": {
    "acronym": "RAILWY",
    "label": "Railway"
  },
  "107": {
    "acronym": "RAPIDS",
    "label": "Rapids"
  },
  "108": {
    "acronym": "RCRTCL",
    "label": "Recommended route centerline"
  },
  "109": {
    "acronym": "RECTRC",
    "label": "Recommended track"
  },
  "110": {
    "acronym": "RCTLPT",
    "label": "Recommended Traffic Lane Part"
  },
  "111": {
    "acronym": "RSCSTA",
    "label": "Rescue station"
  },
  "112": {
    "acronym": "RESARE",
    "label": "Restricted area"
  },
  "113": {
    "acronym": "RETRFL",
    "label": "Retro-reflector"
  },
  "114": {
    "acronym": "RIVERS",
    "label": "River"
  },
  "115": {
    "acronym": "RIVBNK",
    "label": "River bank"
  },
  "116": {
    "acronym": "ROADWY",
    "label": "Road"
  },
  "117": {
    "acronym": "RUNWAY",
    "label": "Runway"
  },
  "118": {
    "acronym": "SNDWAV",
    "label": "Sand waves"
  },
  "119": {
    "acronym": "SEAARE",
    "label": "Sea area / named water area"
  },
  "120": {
    "acronym": "SPLARE",
    "label": "Sea-plane landing area"
  },
  "121": {
    "acronym": "SBDARE",
    "label": "Seabed area"
  },
  "122": {
    "acronym": "SLCONS",
    "label": "Shoreline Construction"
  },
  "123": {
    "acronym": "SISTAT",
    "label": "Signal station, traffic"
  },
  "124": {
    "acronym": "SISTAW",
    "label": "Signal station, warning"
  },
  "125": {
    "acronym": "SILTNK",
    "label": "Silo / tank"
  },
  "126": {
    "acronym": "SLOTOP",
    "label": "Slope topline"
  },
  "127": {
    "acronym": "SLOGRD",
    "label": "Sloping ground"
  },
  "128": {
    "acronym": "SMCFAC",
    "label": "Small craft facility"
  },
  "129": {
    "acronym": "SOUNDG",
    "label": "Sounding"
  },
  "130": {
    "acronym": "SPRING",
    "label": "Spring"
  },
  "131": {
    "acronym": "SQUARE",
    "label": "Square"
  },
  "132": {
    "acronym": "STSLNE",
    "label": "Straight territorial sea baseline"
  },
  "133": {
    "acronym": "SUBTLN",
    "label": "Submarine transit lane"
  },
  "134": {
    "acronym": "SWPARE",
    "label": "Swept Area"
  },
  "135": {
    "acronym": "TESARE",
    "label": "Territorial sea area"
  },
  "136": {
    "acronym": "TS_PRH",
    "label": "Tidal stream - harmonic prediction"
  },
  "137": {
    "acronym": "TS_PNH",
    "label": "Tidal stream - non-harmonic prediction"
  },
  "138": {
    "acronym": "TS_PAD",
    "label": "Tidal stream panel data"
  },
  "139": {
    "acronym": "TS_TIS",
    "label": "Tidal stream - time series"
  },
  "140": {
    "acronym": "T_HMON",
    "label": "Tide - harmonic prediction"
  },
  "141": {
    "acronym": "T_NHMN",
    "label": "Tide - non-harmonic prediction"
  },
  "142": {
    "acronym": "T_TIMS",
    "label": "Tidal stream - time series"
  },
  "143": {
    "acronym": "TIDEWY",
    "label": "Tideway"
  },
  "144": {
    "acronym": "TOPMAR",
    "label": "Top mark"
  },
  "145": {
    "acronym": "TSELNE",
    "label": "Traffic Separation Line"
  },
  "146": {
    "acronym": "TSSBND",
    "label": "Traffic Separation Scheme  Boundary"
  },
  "147": {
    "acronym": "TSSCRS",
    "label": "Traffic Separation Scheme Crossing"
  },
  "148": {
    "acronym": "TSSLPT",
    "label": "Traffic Separation Scheme  Lane part"
  },
  "149": {
    "acronym": "TSSRON",
    "label": "Traffic Separation Scheme  Roundabout"
  },
  "150": {
    "acronym": "TSEZNE",
    "label": "Traffic Separation Zone"
  },
  "151": {
    "acronym": "TUNNEL",
    "label": "Tunnel"
  },
  "152": {
    "acronym": "TWRTPT",
    "label": "Two-way route  part"
  },
  "153": {
    "acronym": "UWTROC",
    "label": "Underwater rock / awash rock"
  },
  "154": {
    "acronym": "UNSARE",
    "label": "Unsurveyed area"
  },
  "155": {
    "acronym": "VEGATN",
    "label": "Vegetation"
  },
  "156": {
    "acronym": "WATTUR",
    "label": "Water turbulence"
  },
  "157": {
    "acronym": "WATFAL",
    "label": "Waterfall"
  },
  "158": {
    "acronym": "WEDKLP",
    "label": "Weed/Kelp"
  },
  "159": {
    "acronym": "WRECKS",
    "label": "Wreck"
  },
  "160": {
    "acronym": "TS_FEB",
    "label": "Tidal stream - flood/ebb"
  },
  "161": {
    "acronym": "ARCSLN",
    "label": "Archipelagix Sea Lane"
  },
  "162": {
    "acronym": "ASLXIS",
    "label": "Archipelagix Sea Lane axis"
  },
  "163": {
    "acronym": "NEWOBJ",
    "label": "New object"
  },
  "300": {
    "acronym": "M_ACCY",
    "label": "Accuracy of data"
  },
  "301": {
    "acronym": "M_CSCL",
    "label": "Compilation scale of data"
  },
  "302": {
    "acronym": "M_COVR",
    "label": "Coverage"
  },
  "303": {
    "acronym": "M_HDAT",
    "label": "Horizontal datum of data"
  },
  "304": {
    "acronym": "M_HOPA",
    "label": "Horizontal datum shift parameters"
  },
  "305": {
    "acronym": "M_NPUB",
    "label": "Nautical publication information"
  },
  "306": {
    "acronym": "M_NSYS",
    "label": "Navigational system of marks"
  },
  "307": {
    "acronym": "M_PROD",
    "label": "Production information"
  },
  "308": {
    "acronym": "M_QUAL",
    "label": "Quality of data"
  },
  "309": {
    "acronym": "M_SDAT",
    "label": "Sounding datum"
  },
  "310": {
    "acronym": "M_SREL",
    "label": "Survey reliability"
  },
  "311": {
    "acronym": "M_UNIT",
    "label": "Units of measurement of data"
  },
  "312": {
    "acronym": "M_VDAT",
    "label": "Vertical datum of data"
  },
  "400": {
    "acronym": "C_AGGR",
    "label": "Aggregation"
  },
  "401": {
    "acronym": "C_ASSO",
    "label": "Association"
  },
  "402": {
    "acronym": "C_STAC",
    "label": "Stacked on/stacked under"
  },
  "500": {
    "acronym": "$AREAS",
    "label": "Cartographic area"
  },
  "501": {
    "acronym": "$LINES",
    "label": "Cartographic line"
  },
  "502": {
    "acronym": "$CSYMB",
    "label": "Cartographic symbol"
  },
  "503": {
    "acronym": "$COMPS",
    "label": "Compass"
  },
  "504": {
    "acronym": "$TEXTS",
    "label": "Text"
  },
  "17000": {
    "acronym": "achbrt",
    "label": "Anchor berth"
  },
  "17001": {
    "acronym": "achare",
    "label": "Anchorage area"
  },
  "17002": {
    "acronym": "canbnk",
    "label": "Canal bank"
  },
  "17003": {
    "acronym": "depare",
    "label": "Depth area"
  },
  "17004": {
    "acronym": "dismar",
    "label": "Distance mark"
  },
  "17005": {
    "acronym": "resare",
    "label": "Restricted area"
  },
  "17006": {
    "acronym": "rivbnk",
    "label": "River bank"
  },
  "17007": {
    "acronym": "sistat",
    "label": "Signal station traffic"
  },
  "17008": {
    "acronym": "sistaw",
    "label": "Signal station warning"
  },
  "17009": {
    "acronym": "topmar",
    "label": "Top Mark"
  },
  "17010": {
    "acronym": "berths",
    "label": "Berth berths"
  },
  "17011": {
    "acronym": "bridge",
    "label": "Bridge"
  },
  "17012": {
    "acronym": "cblohd",
    "label": "Cable overhead"
  },
  "17013": {
    "acronym": "feryrt",
    "label": "Ferry route"
  },
  "17014": {
    "acronym": "hrbare",
    "label": "Harbour Area"
  },
  "17015": {
    "acronym": "hrbfac",
    "label": "Harbour Facilities"
  },
  "17016": {
    "acronym": "lokbsn",
    "label": "Lock Basin"
  },
  "17017": {
    "acronym": "rdocal",
    "label": "Radio calling-in point"
  },
  "17018": {
    "acronym": "m_nsys",
    "label": "Navigational system of marks"
  },
  "17050": {
    "acronym": "notmrk",
    "label": "Notice mark"
  },
  "17051": {
    "acronym": "wtwaxs",
    "label": "Waterway axis"
  },
  "17052": {
    "acronym": "wtwprf",
    "label": "Waterway profile"
  },
  "17053": {
    "acronym": "brgare",
    "label": "Bridge area"
  },
  "17054": {
    "acronym": "bunsta",
    "label": "Bunker station"
  },
  "17055": {
    "acronym": "comare",
    "label": "Communication Area"
  },
  "17056": {
    "acronym": "hrbbsn",
    "label": "Harbour Basin"
  },
  "17057": {
    "acronym": "lokare",
    "label": "Lock area"
  },
  "17058": {
    "acronym": "lkbspt",
    "label": "Lock basin part"
  },
  "17059": {
    "acronym": "prtare",
    "label": "Port Area"
  },
  "17060": {
    "acronym": "bcnwtw",
    "label": "Beacon water-way"
  },
  "17061": {
    "acronym": "boywtw",
    "label": "Buoy water-way"
  },
  "17062": {
    "acronym": "refdmp",
    "label": "Refuse dump"
  },
  "17063": {
    "acronym": "rtplpt",
    "label": "Route planning point"
  },
  "17064": {
    "acronym": "termnl",
    "label": "Terminal"
  },
  "17065": {
    "acronym": "trnbsn",
    "label": "Turning basin"
  },
  "20484": {
    "acronym": "atsctl",
    "label": "ATS Route Centreline"
  },
  "20485": {
    "acronym": "airres + catasr",
    "label": "Airspace Restriction"
  },
  "20486": {
    "acronym": "imgare",
    "label": "Area of Imagery Coverage"
  },
  "20487": {
    "acronym": "bchext",
    "label": "Beach Exit"
  },
  "20488": {
    "acronym": "bchprf",
    "label": "Beach Profile"
  },
  "20489": {
    "acronym": "bchare",
    "label": "Beach Survey"
  },
  "20490": {
    "acronym": "bedare",
    "label": "Bedrock area"
  },
  "20491": {
    "acronym": "botmft + catbot",
    "label": "Bottom Feature"
  },
  "20492": {
    "acronym": "centre",
    "label": "Centre Line"
  },
  "20494": {
    "acronym": "histob",
    "label": "Contact History"
  },
  "20495": {
    "acronym": "ctlasp + catcas",
    "label": "Controlled airspace"
  },
  "20496": {
    "acronym": "divloc",
    "label": "Diving Location"
  },
  "20497": {
    "acronym": "watloc",
    "label": "Drinking Water Location"
  },
  "20498": {
    "acronym": "drpzne",
    "label": "Drop Zone"
  },
  "20499": {
    "acronym": "envare",
    "label": "Environmentally Sensitive Area"
  },
  "20500": {
    "acronym": "fshare",
    "label": "Fishing Activity Area"
  },
  "20501": {
    "acronym": "iscour",
    "label": "Impact Scour"
  },
  "20502": {
    "acronym": "lngare",
    "label": "Landing Area"
  },
  "20503": {
    "acronym": "lndplc",
    "label": "Landing Place"
  },
  "20504": {
    "acronym": "lndpnt",
    "label": "Landing Point"
  },
  "20505": {
    "acronym": "lndste",
    "label": "Landing Site"
  },
  "20506": {
    "acronym": "lndstp",
    "label": "Landing Strip"
  },
  "20507": {
    "acronym": "lndzne",
    "label": "Landing Zone"
  },
  "20508": {
    "acronym": "marman + catmma",
    "label": "Marine management area"
  },
  "20509": {
    "acronym": "msiare",
    "label": "Maritime Safety Information area"
  },
  "20510": {
    "acronym": "mcmare",
    "label": "MCM Area"
  },
  "20511": {
    "acronym": "mexasp + catmea",
    "label": "Military exercise airspace"
  },
  "20513": {
    "acronym": "patare + catpat",
    "label": "Patrol area"
  },
  "20514": {
    "acronym": "qroute",
    "label": "Q-Route Leg"
  },
  "20515": {
    "acronym": "rdoare",
    "label": "Radio broadcast area"
  },
  "20516": {
    "acronym": "regasp",
    "label": "Regulated airspace"
  },
  "20517": {
    "acronym": "sedlay",
    "label": "Geological Layer"
  },
  "20518": {
    "acronym": "seiare",
    "label": "Seismic Activity Area"
  },
  "20519": {
    "acronym": "senanm",
    "label": "Sensor Anomaly"
  },
  "20520": {
    "acronym": "shlloc",
    "label": "Shelter Location"
  },
  "20521": {
    "acronym": "seddep",
    "label": "Superficial Sediment Deposits"
  },
  "20522": {
    "acronym": "trfare",
    "label": "Trafficability Area"
  },
  "20523": {
    "acronym": "twlscr",
    "label": "Trawl Scours"
  },
  "20524": {
    "acronym": "turnpt",
    "label": "Turning point"
  },
  "20525": {
    "acronym": "viewpt",
    "label": "Viewpoint"
  },
  "20526": {
    "acronym": "btdare",
    "label": "Bottom Tactical Data Area"
  },
  "20527": {
    "acronym": "bprare",
    "label": "Burial Probability Area"
  },
  "20528": {
    "acronym": "lsrare",
    "label": "Leisure Activity Area"
  },
  "20529": {
    "acronym": "pfdare",
    "label": "Performance Data Area"
  },
  "20530": {
    "acronym": "resloc",
    "label": "Resource Location"
  },
  "20531": {
    "acronym": "rkdare",
    "label": "Risk Data Area"
  },
  "20532": {
    "acronym": "navaid + CATROS",
    "label": "Navigation system (NAVAID)"
  },
  "20533": {
    "acronym": "intwtr",
    "label": "Internal Waters Area "
  },
  "20534": {
    "acronym": "seaice",
    "label": "Sea Ice"
  },
  "20535": {
    "acronym": "iceadv",
    "label": "Ice Advisory Area"
  },
  "20536": {
    "acronym": "brgare",
    "label": "Iceberg Area"
  },
  "20537": {
    "acronym": "lndice",
    "label": "Land Ice"
  },
  "20538": {
    "acronym": "icelin",
    "label": "Ice Line"
  },
  "20539": {
    "acronym": "icerte",
    "label": "Ice Route"
  },
  "20540": {
    "acronym": "icepol",
    "label": "Ice Polynya"
  },
  "20541": {
    "acronym": "icelea",
    "label": "Ice Lead"
  },
  "20542": {
    "acronym": "icebrg",
    "label": "Iceberg"
  },
  "20543": {
    "acronym": "icemov",
    "label": "Ice Movement"
  },
  "20544": {
    "acronym": "tfcrte",
    "label": "Traffic route"
  },
  "20717": {
    "acronym": "u_defd",
    "label": "User Defined"
  },
  "20718": {
    "acronym": "smalbo",
    "label": "Small Bottom Object"
  },
  "21484": {
    "acronym": "m_conf + catcnf",
    "label": "Completeness for the product specification"
  },
  "21485": {
    "acronym": "m_clas",
    "label": "Security Classification Information"
  },
  "21486": {
    "acronym": "m_vers",
    "label": "Vertical Datum Shift Area"
  },
  "21487": {
    "acronym": "m_line",
    "label": "Defined Straight Lines"
  }
};

/** Attribute acronym (e.g. "DRVAL1", "WATLEV") → official label + value type. */
export const ATTRIBUTES: Record<string, { label: string; type: AttributeType }> =
  {
  "AGENCY": {
    "label": "Agency responsible for production",
    "type": "string"
  },
  "BCNSHP": {
    "label": "Beacon shape",
    "type": "enum"
  },
  "BUISHP": {
    "label": "Building shape",
    "type": "enum"
  },
  "BOYSHP": {
    "label": "Buoy shape",
    "type": "enum"
  },
  "BURDEP": {
    "label": "Buried depth",
    "type": "float"
  },
  "CALSGN": {
    "label": "Call sign",
    "type": "string"
  },
  "CATAIR": {
    "label": "Category of airport/airfield",
    "type": "list"
  },
  "CATACH": {
    "label": "Category of anchorage",
    "type": "list"
  },
  "CATBRG": {
    "label": "Category of bridge",
    "type": "list"
  },
  "CATBUA": {
    "label": "Category of built-up area",
    "type": "enum"
  },
  "CATCBL": {
    "label": "Category of cable",
    "type": "enum"
  },
  "CATCAN": {
    "label": "Category of canal",
    "type": "enum"
  },
  "CATCAM": {
    "label": "Category of cardinal mark",
    "type": "enum"
  },
  "CATCHP": {
    "label": "Category of checkpoint",
    "type": "enum"
  },
  "CATCOA": {
    "label": "Category of coastline",
    "type": "enum"
  },
  "CATCTR": {
    "label": "Category of control point",
    "type": "enum"
  },
  "CATCON": {
    "label": "Category of conveyor",
    "type": "enum"
  },
  "CATCOV": {
    "label": "Category of coverage",
    "type": "enum"
  },
  "CATCRN": {
    "label": "Category of crane",
    "type": "enum"
  },
  "CATDAM": {
    "label": "Category of dam",
    "type": "enum"
  },
  "CATDIS": {
    "label": "Category of distance mark",
    "type": "enum"
  },
  "CATDOC": {
    "label": "Category of dock",
    "type": "enum"
  },
  "CATDPG": {
    "label": "Category of dumping ground",
    "type": "list"
  },
  "CATFNC": {
    "label": "Category of fence/wall",
    "type": "enum"
  },
  "CATFRY": {
    "label": "Category of ferry",
    "type": "enum"
  },
  "CATFIF": {
    "label": "Category of fishing  facility",
    "type": "enum"
  },
  "CATFOG": {
    "label": "Category of fog signal",
    "type": "enum"
  },
  "CATFOR": {
    "label": "Category of fortified structure",
    "type": "enum"
  },
  "CATGAT": {
    "label": "Category of gate",
    "type": "enum"
  },
  "CATHAF": {
    "label": "Category of harbour facility",
    "type": "list"
  },
  "CATHLK": {
    "label": "Category of hulk",
    "type": "list"
  },
  "CATICE": {
    "label": "Category of ice",
    "type": "enum"
  },
  "CATINB": {
    "label": "Category of installation buoy",
    "type": "enum"
  },
  "CATLND": {
    "label": "Category of land region",
    "type": "list"
  },
  "CATLMK": {
    "label": "Category of landmark",
    "type": "list"
  },
  "CATLAM": {
    "label": "Category of lateral mark",
    "type": "enum"
  },
  "CATLIT": {
    "label": "Category of light",
    "type": "list"
  },
  "CATMFA": {
    "label": "Category of marine farm/culture",
    "type": "enum"
  },
  "CATMPA": {
    "label": "Category of military practice area",
    "type": "list"
  },
  "CATMOR": {
    "label": "Category of mooring/warping facility",
    "type": "enum"
  },
  "CATNAV": {
    "label": "Category of navigation line",
    "type": "enum"
  },
  "CATOBS": {
    "label": "Category of obstruction",
    "type": "enum"
  },
  "CATOFP": {
    "label": "Category of offshore platform",
    "type": "list"
  },
  "CATOLB": {
    "label": "Category of oil barrier",
    "type": "enum"
  },
  "CATPLE": {
    "label": "Category of pile",
    "type": "enum"
  },
  "CATPIL": {
    "label": "Category of pilot boarding place",
    "type": "enum"
  },
  "CATPIP": {
    "label": "Category of pipeline / pipe",
    "type": "list"
  },
  "CATPRA": {
    "label": "Category of production area",
    "type": "enum"
  },
  "CATPYL": {
    "label": "Category of pylon",
    "type": "enum"
  },
  "CATQUA": {
    "label": "Category of quality of data",
    "type": "enum"
  },
  "CATRAS": {
    "label": "Category of radar station",
    "type": "enum"
  },
  "CATRTB": {
    "label": "Category of radar transponder beacon",
    "type": "enum"
  },
  "CATROS": {
    "label": "Category of radio station",
    "type": "list"
  },
  "CATTRK": {
    "label": "Category of recommended track",
    "type": "enum"
  },
  "CATRSC": {
    "label": "Category of rescue station",
    "type": "list"
  },
  "CATREA": {
    "label": "Category of restricted area",
    "type": "list"
  },
  "CATROD": {
    "label": "Category of road",
    "type": "enum"
  },
  "CATRUN": {
    "label": "Category of runway",
    "type": "enum"
  },
  "CATSEA": {
    "label": "Category of sea area",
    "type": "enum"
  },
  "CATSLC": {
    "label": "Category of shoreline construction",
    "type": "enum"
  },
  "CATSIT": {
    "label": "Category of signal station, traffic",
    "type": "list"
  },
  "CATSIW": {
    "label": "Category of signal station, warning",
    "type": "list"
  },
  "CATSIL": {
    "label": "Category of silo/tank",
    "type": "enum"
  },
  "CATSLO": {
    "label": "Category of slope",
    "type": "enum"
  },
  "CATSCF": {
    "label": "Category of small craft facility",
    "type": "list"
  },
  "CATSPM": {
    "label": "Category of special purpose mark",
    "type": "list"
  },
  "CATTSS": {
    "label": "Category of Traffic Separation Scheme",
    "type": "enum"
  },
  "CATVEG": {
    "label": "Category of vegetation",
    "type": "list"
  },
  "CATWAT": {
    "label": "Category of water turbulence",
    "type": "enum"
  },
  "CATWED": {
    "label": "Category of weed/kelp",
    "type": "enum"
  },
  "CATWRK": {
    "label": "Category of wreck",
    "type": "enum"
  },
  "CATZOC": {
    "label": "Category of zone of confidence data",
    "type": "enum"
  },
  "$SPACE": {
    "label": "Character spacing",
    "type": "enum"
  },
  "$CHARS": {
    "label": "Character specification",
    "type": "string"
  },
  "COLOUR": {
    "label": "Colour",
    "type": "list"
  },
  "COLPAT": {
    "label": "Colour pattern",
    "type": "list"
  },
  "COMCHA": {
    "label": "Communication channel",
    "type": "string"
  },
  "$CSIZE": {
    "label": "Compass size",
    "type": "float"
  },
  "CPDATE": {
    "label": "Compilation date",
    "type": "string"
  },
  "CSCALE": {
    "label": "Compilation scale",
    "type": "int"
  },
  "CONDTN": {
    "label": "Condition",
    "type": "enum"
  },
  "CONRAD": {
    "label": "Conspicuous, Radar",
    "type": "enum"
  },
  "CONVIS": {
    "label": "Conspicuous, visual",
    "type": "enum"
  },
  "CURVEL": {
    "label": "Current velocity",
    "type": "float"
  },
  "DATEND": {
    "label": "Date end",
    "type": "string"
  },
  "DATSTA": {
    "label": "Date start",
    "type": "string"
  },
  "DRVAL1": {
    "label": "Depth range value 1",
    "type": "float"
  },
  "DRVAL2": {
    "label": "Depth range value 2",
    "type": "float"
  },
  "DUNITS": {
    "label": "Depth units",
    "type": "enum"
  },
  "ELEVAT": {
    "label": "Elevation",
    "type": "float"
  },
  "ESTRNG": {
    "label": "Estimated range of transmission",
    "type": "float"
  },
  "EXCLIT": {
    "label": "Exhibition condition of light",
    "type": "enum"
  },
  "EXPSOU": {
    "label": "Exposition of sounding",
    "type": "enum"
  },
  "FUNCTN": {
    "label": "Function",
    "type": "list"
  },
  "HEIGHT": {
    "label": "Height",
    "type": "float"
  },
  "HUNITS": {
    "label": "Height/length units",
    "type": "enum"
  },
  "HORACC": {
    "label": "Horizontal accuracy",
    "type": "float"
  },
  "HORCLR": {
    "label": "Horizontal clearance",
    "type": "float"
  },
  "HORLEN": {
    "label": "Horizontal length",
    "type": "float"
  },
  "HORWID": {
    "label": "Horizontal width",
    "type": "float"
  },
  "ICEFAC": {
    "label": "Ice factor",
    "type": "float"
  },
  "INFORM": {
    "label": "Information",
    "type": "string"
  },
  "JRSDTN": {
    "label": "Jurisdiction",
    "type": "enum"
  },
  "$JUSTH": {
    "label": "Justification - horizontal",
    "type": "enum"
  },
  "$JUSTV": {
    "label": "Justification - vertical",
    "type": "enum"
  },
  "LIFCAP": {
    "label": "Lifting capacity",
    "type": "float"
  },
  "LITCHR": {
    "label": "Light characteristic",
    "type": "enum"
  },
  "LITVIS": {
    "label": "Light visibility",
    "type": "list"
  },
  "MARSYS": {
    "label": "Marks navigational - System of",
    "type": "enum"
  },
  "MLTYLT": {
    "label": "Multiplicity of lights",
    "type": "int"
  },
  "NATION": {
    "label": "Nationality",
    "type": "string"
  },
  "NATCON": {
    "label": "Nature of construction",
    "type": "list"
  },
  "NATSUR": {
    "label": "Nature of surface",
    "type": "list"
  },
  "NATQUA": {
    "label": "Nature of surface - qualifying terms",
    "type": "list"
  },
  "NMDATE": {
    "label": "Notice to Mariners date",
    "type": "string"
  },
  "OBJNAM": {
    "label": "Object name",
    "type": "string"
  },
  "ORIENT": {
    "label": "Orientation",
    "type": "float"
  },
  "PEREND": {
    "label": "Periodic date end",
    "type": "string"
  },
  "PERSTA": {
    "label": "Periodic date start",
    "type": "string"
  },
  "PICREP": {
    "label": "Pictorial representation",
    "type": "string"
  },
  "PILDST": {
    "label": "Pilot district",
    "type": "string"
  },
  "PRCTRY": {
    "label": "Producing country",
    "type": "string"
  },
  "PRODCT": {
    "label": "Product",
    "type": "list"
  },
  "PUBREF": {
    "label": "Publication reference",
    "type": "string"
  },
  "QUASOU": {
    "label": "Quality of sounding measurement",
    "type": "list"
  },
  "RADWAL": {
    "label": "Radar wave length",
    "type": "string"
  },
  "RADIUS": {
    "label": "Radius",
    "type": "float"
  },
  "RECDAT": {
    "label": "Recording date",
    "type": "string"
  },
  "RECIND": {
    "label": "Recording indication",
    "type": "string"
  },
  "RYRMGV": {
    "label": "Reference year for magnetic variation",
    "type": "string"
  },
  "RESTRN": {
    "label": "Restriction",
    "type": "list"
  },
  "SCAMAX": {
    "label": "Scale maximum",
    "type": "int"
  },
  "SCAMIN": {
    "label": "Scale minimum",
    "type": "int"
  },
  "SCVAL1": {
    "label": "Scale value one",
    "type": "int"
  },
  "SCVAL2": {
    "label": "Scale value two",
    "type": "int"
  },
  "SECTR1": {
    "label": "Sector limit one",
    "type": "float"
  },
  "SECTR2": {
    "label": "Sector limit two",
    "type": "float"
  },
  "SHIPAM": {
    "label": "Shift parameters",
    "type": "string"
  },
  "SIGFRQ": {
    "label": "Signal frequency",
    "type": "int"
  },
  "SIGGEN": {
    "label": "Signal generation",
    "type": "enum"
  },
  "SIGGRP": {
    "label": "Signal group",
    "type": "string"
  },
  "SIGPER": {
    "label": "Signal period",
    "type": "float"
  },
  "SIGSEQ": {
    "label": "Signal sequence",
    "type": "string"
  },
  "SOUACC": {
    "label": "Sounding accuracy",
    "type": "float"
  },
  "SDISMX": {
    "label": "Sounding distance - maximum",
    "type": "int"
  },
  "SDISMN": {
    "label": "Sounding distance - minimum",
    "type": "int"
  },
  "SORDAT": {
    "label": "Source date",
    "type": "string"
  },
  "SORIND": {
    "label": "Source indication",
    "type": "string"
  },
  "STATUS": {
    "label": "Status",
    "type": "list"
  },
  "SURATH": {
    "label": "Survey authority",
    "type": "string"
  },
  "SUREND": {
    "label": "Survey date - end",
    "type": "string"
  },
  "SURSTA": {
    "label": "Survey date - start",
    "type": "string"
  },
  "SURTYP": {
    "label": "Survey type",
    "type": "list"
  },
  "$SCALE": {
    "label": "Symbol scaling factor",
    "type": "float"
  },
  "$SCODE": {
    "label": "Symbolization code",
    "type": "string"
  },
  "TECSOU": {
    "label": "Technique of sounding measurement",
    "type": "list"
  },
  "$TXSTR": {
    "label": "Text string",
    "type": "string"
  },
  "TXTDSC": {
    "label": "Textual description",
    "type": "string"
  },
  "TS_TSP": {
    "label": "Tidal stream - panel values",
    "type": "string"
  },
  "TS_TSV": {
    "label": "Tidal stream, current - time series values",
    "type": "string"
  },
  "T_ACWL": {
    "label": "Tide - accuracy of water level",
    "type": "enum"
  },
  "T_HWLW": {
    "label": "Tide - high and low water values",
    "type": "string"
  },
  "T_MTOD": {
    "label": "Tide - method of tidal prediction",
    "type": "enum"
  },
  "T_THDF": {
    "label": "Tide - time and height differences",
    "type": "string"
  },
  "T_TINT": {
    "label": "Tide, current - time interval of values",
    "type": "int"
  },
  "T_TSVL": {
    "label": "Tide - time series values",
    "type": "string"
  },
  "T_VAHC": {
    "label": "Tide - value of harmonic constituents",
    "type": "string"
  },
  "TIMEND": {
    "label": "Time end",
    "type": "string"
  },
  "TIMSTA": {
    "label": "Time start",
    "type": "string"
  },
  "$TINTS": {
    "label": "Tint",
    "type": "enum"
  },
  "TOPSHP": {
    "label": "Topmark/daymark shape",
    "type": "enum"
  },
  "TRAFIC": {
    "label": "Traffic flow",
    "type": "enum"
  },
  "VALACM": {
    "label": "Value of annual change in magnetic variation",
    "type": "float"
  },
  "VALDCO": {
    "label": "Value of depth contour",
    "type": "float"
  },
  "VALLMA": {
    "label": "Value of local magnetic anomaly",
    "type": "float"
  },
  "VALMAG": {
    "label": "Value of magnetic variation",
    "type": "float"
  },
  "VALMXR": {
    "label": "Value of maximum range",
    "type": "float"
  },
  "VALNMR": {
    "label": "Value of nominal range",
    "type": "float"
  },
  "VALSOU": {
    "label": "Value of sounding",
    "type": "float"
  },
  "VERACC": {
    "label": "Vertical accuracy",
    "type": "float"
  },
  "VERCLR": {
    "label": "Vertical clearance",
    "type": "float"
  },
  "VERCCL": {
    "label": "Vertical clearance, closed",
    "type": "float"
  },
  "VERCOP": {
    "label": "Vertical clearance, open",
    "type": "float"
  },
  "VERCSA": {
    "label": "Vertical clearance, safe",
    "type": "float"
  },
  "VERDAT": {
    "label": "Vertical datum",
    "type": "enum"
  },
  "VERLEN": {
    "label": "Vertical length",
    "type": "float"
  },
  "WATLEV": {
    "label": "Water level effect",
    "type": "enum"
  },
  "CAT_TS": {
    "label": "Category of Tidal stream",
    "type": "enum"
  },
  "PUNITS": {
    "label": "Positional accuracy units",
    "type": "enum"
  },
  "CLSDEF": {
    "label": "Object class definition",
    "type": "string"
  },
  "CLSNAM": {
    "label": "Object class name",
    "type": "string"
  },
  "SYMINS": {
    "label": "Symbol instruction",
    "type": "string"
  },
  "NINFOM": {
    "label": "Information in national language",
    "type": "string"
  },
  "NOBJNM": {
    "label": "Object name in national language",
    "type": "string"
  },
  "NPLDST": {
    "label": "Pilot district in national language",
    "type": "string"
  },
  "$NTXST": {
    "label": "Text string in national language",
    "type": "string"
  },
  "NTXTDS": {
    "label": "Textual description in national language",
    "type": "string"
  },
  "HORDAT": {
    "label": "Horizontal datum",
    "type": "enum"
  },
  "POSACC": {
    "label": "Positional Accuracy",
    "type": "float"
  },
  "QUAPOS": {
    "label": "Quality of position",
    "type": "enum"
  },
  "###": {
    "label": "###40000 comes from past s57attributes_iw.csv (Inland Waterways)",
    "type": "string"
  },
  "catach": {
    "label": "Category of Anchorage area",
    "type": "list"
  },
  "catdis": {
    "label": "Category of distance mark",
    "type": "enum"
  },
  "catsit": {
    "label": "Category of signal station trafficcatsit",
    "type": "list"
  },
  "catsiw": {
    "label": "Category of signal station warning",
    "type": "list"
  },
  "restrn": {
    "label": "Restriction",
    "type": "list"
  },
  "verdat": {
    "label": "Vertical datum",
    "type": "enum"
  },
  "catbrg": {
    "label": "Category of bridge",
    "type": "list"
  },
  "catfry": {
    "label": "Category of ferry",
    "type": "list"
  },
  "cathaf": {
    "label": "Category of harbour facilities",
    "type": "list"
  },
  "marsys": {
    "label": "Marks navigational  System of",
    "type": "enum"
  },
  "addmrk": {
    "label": "Additional mark",
    "type": "list"
  },
  "catbnk": {
    "label": "Category of bank",
    "type": "enum"
  },
  "catnmk": {
    "label": "Category of notice mark",
    "type": "enum"
  },
  "clsdng": {
    "label": "Class of dangerous cargo",
    "type": "enum"
  },
  "dirimp": {
    "label": "Direction of impact",
    "type": "list"
  },
  "disbk1": {
    "label": "Distance from bank",
    "type": "float"
  },
  "disbk2": {
    "label": "Distance from bank",
    "type": "float"
  },
  "disipu": {
    "label": "Distance of impact, upstream",
    "type": "float"
  },
  "disipd": {
    "label": "Distance of impact, downstream",
    "type": "float"
  },
  "eleva1": {
    "label": "Elevation 1",
    "type": "float"
  },
  "eleva2": {
    "label": "Elevation 2",
    "type": "float"
  },
  "fnctnm": {
    "label": "Function of notice mark",
    "type": "enum"
  },
  "wtwdis": {
    "label": "Waterway distance",
    "type": "float"
  },
  "bunves": {
    "label": "Bunker vessel",
    "type": "enum"
  },
  "catbrt": {
    "label": "Category of berth",
    "type": "list"
  },
  "catbun": {
    "label": "Category of bunker",
    "type": "list"
  },
  "catccl": {
    "label": "Category of CEMT class",
    "type": "list"
  },
  "catcom": {
    "label": "Category of communication",
    "type": "list"
  },
  "cathbr": {
    "label": "Category of harbour area",
    "type": "list"
  },
  "catrfd": {
    "label": "Category of refuse dump",
    "type": "list"
  },
  "cattml": {
    "label": "Category of terminal",
    "type": "list"
  },
  "comctn": {
    "label": "Communication",
    "type": "string"
  },
  "horcll": {
    "label": "Horizontal clearance, length",
    "type": "float"
  },
  "horclw": {
    "label": "Horizontal clearance, width",
    "type": "float"
  },
  "trshgd": {
    "label": "Transshipping goods",
    "type": "list"
  },
  "unlocd": {
    "label": "UN Location Code",
    "type": "string"
  },
  "catwwm": {
    "label": "Category of waterway mark",
    "type": "enum"
  },
  "databa": {
    "label": "Abandonment Date",
    "type": "string"
  },
  "attutn": {
    "label": "Attenuation",
    "type": "float"
  },
  "vesbem": {
    "label": "Beam of Vessel",
    "type": "float"
  },
  "bearng": {
    "label": "Bearing",
    "type": "float"
  },
  "blndzn": {
    "label": "Blind Zone",
    "type": "string"
  },
  "brktyp": {
    "label": "Breaker Type",
    "type": "enum"
  },
  "bulkdn": {
    "label": "Density",
    "type": "float"
  },
  "brmchm": {
    "label": "Burial Mechanism",
    "type": "enum"
  },
  "brpctg": {
    "label": "Burial Percentage",
    "type": "int"
  },
  "brperd": {
    "label": "Burial Period",
    "type": "int"
  },
  "brprob": {
    "label": "Burial Probability",
    "type": "enum"
  },
  "orcard": {
    "label": "Cardinal Point Orientation",
    "type": "enum"
  },
  "catadm": {
    "label": "Category of administration area",
    "type": "enum"
  },
  "catasr": {
    "label": "Category of airspace restriction",
    "type": "enum"
  },
  "N/A": {
    "label": "Security classification",
    "type": "string"
  },
  "catbot": {
    "label": "Bottom Feature Classification",
    "type": "enum"
  },
  "catcgs": {
    "label": "Category of coastguard station",
    "type": "enum"
  },
  "catcas": {
    "label": "Category of controlled airspace",
    "type": "enum"
  },
  "catfsh": {
    "label": "Fishing Activity",
    "type": "enum"
  },
  "catimg": {
    "label": "Type of Imagery",
    "type": "list"
  },
  "catmma": {
    "label": "Category of marine management area",
    "type": "enum"
  },
  "catmsi": {
    "label": "Category of maritime safety information",
    "type": "enum"
  },
  "catmea": {
    "label": "Category of military exercise airspace ",
    "type": "enum"
  },
  "catpat": {
    "label": "Category of patrol area",
    "type": "enum"
  },
  "catrep": {
    "label": "Category of reporting/radio calling-in point",
    "type": "enum"
  },
  "catsbl": {
    "label": "Category of territorial sea baseline",
    "type": "enum"
  },
  "cattrf": {
    "label": "Trafficability",
    "type": "enum"
  },
  "comsys": {
    "label": "Command System",
    "type": "string"
  },
  "caircd": {
    "label": "Controlled airspace class designation",
    "type": "enum"
  },
  "authty": {
    "label": "Controlling authority",
    "type": "string"
  },
  "scrdim": {
    "label": "Current Scour Dimensions",
    "type": "string"
  },
  "dgmrlf": {
    "label": "Dangerous Marine and Land Life",
    "type": "list"
  },
  "datsnk": {
    "label": "Date Sunk",
    "type": "string"
  },
  "debfld": {
    "label": "Debris Field",
    "type": "string"
  },
  "depact": {
    "label": "Depth of Activity",
    "type": "float"
  },
  "deplyr": {
    "label": "Depth of Layer",
    "type": "float"
  },
  "discon": {
    "label": "Distance from Small Bottom Object",
    "type": "float"
  },
  "dttdep": {
    "label": "Diver’s Thrust Test Depth",
    "type": "enum"
  },
  "dttnum": {
    "label": "Diver’s Thrust Test Number",
    "type": "int"
  },
  "divact": {
    "label": "Diving Activity",
    "type": "enum"
  },
  "vesdgh": {
    "label": "Draught of Vessel",
    "type": "float"
  },
  "exitus": {
    "label": "Exit Usability",
    "type": "enum"
  },
  "fldnam": {
    "label": "Field Name",
    "type": "string"
  },
  "datfir": {
    "label": "First Detection Year",
    "type": "string"
  },
  "senfir": {
    "label": "First Sensor",
    "type": "enum"
  },
  "sorfir": {
    "label": "First Source",
    "type": "enum"
  },
  "folinx": {
    "label": "Foliar Index",
    "type": "float"
  },
  "gascon": {
    "label": "Gas Content",
    "type": "int"
  },
  "gendep": {
    "label": "General Water Depth",
    "type": "int"
  },
  "gradnt": {
    "label": "Gradient",
    "type": "enum"
  },
  "grnsiz": {
    "label": "Grain Size",
    "type": "float"
  },
  "incltn": {
    "label": "Inclination",
    "type": "float"
  },
  "datlst": {
    "label": "Last Detection Year",
    "type": "string"
  },
  "senlst": {
    "label": "Last Sensor",
    "type": "enum"
  },
  "sorlst": {
    "label": "Last Source",
    "type": "enum"
  },
  "layptm": {
    "label": "Lay Platform",
    "type": "enum"
  },
  "layrfn": {
    "label": "Lay Reference Number",
    "type": "string"
  },
  "laytim": {
    "label": "Lay Time",
    "type": "string"
  },
  "laynum": {
    "label": "Layer Number",
    "type": "int"
  },
  "legsta": {
    "label": "Legal Status",
    "type": "string"
  },
  "veslen": {
    "label": "Length of Vessel",
    "type": "float"
  },
  "madsig": {
    "label": "Magnetic Anomaly Detector (MAD) Signature",
    "type": "enum"
  },
  "magint": {
    "label": "Magnetic Intensity",
    "type": "int"
  },
  "msstrg": {
    "label": "Mean Shear Strength",
    "type": "float"
  },
  "migdir": {
    "label": "Migration Direction",
    "type": "int"
  },
  "migspd": {
    "label": "Migration Speed",
    "type": "float"
  },
  "milden": {
    "label": "Milec Density",
    "type": "enum"
  },
  "mnimnc": {
    "label": "Mine Index Mine Case",
    "type": "enum"
  },
  "mnimnt": {
    "label": "Mine Index Mine Type",
    "type": "list"
  },
  "minern": {
    "label": "Mine Reference Number",
    "type": "string"
  },
  "mhclas": {
    "label": "Mine-Hunting Classification",
    "type": "enum"
  },
  "mnhsys": {
    "label": "Minehunting System",
    "type": "string"
  },
  "mnssys": {
    "label": "Minesweeping System",
    "type": "string"
  },
  "miscls": {
    "label": "Mission Classification",
    "type": "enum"
  },
  "miscom": {
    "label": "Mission Comments",
    "type": "string"
  },
  "misdat": {
    "label": "Mission Date",
    "type": "string"
  },
  "misnme": {
    "label": "Mission Name",
    "type": "string"
  },
  "mwdcrn": {
    "label": "MWDC Reference Number",
    "type": "string"
  },
  "natsed": {
    "label": "Nature of Geological Layer",
    "type": "enum"
  },
  "navsys": {
    "label": "Navigation System",
    "type": "string"
  },
  "nomden": {
    "label": "NOMBO Density",
    "type": "enum"
  },
  "notfnd": {
    "label": "Not Found",
    "type": "string"
  },
  "nmprob": {
    "label": "Number of Previous Observations",
    "type": "int"
  },
  "oprtor": {
    "label": "Operator",
    "type": "string"
  },
  "orbobn": {
    "label": "Orientation of Best Observation",
    "type": "float"
  },
  "orgdat": {
    "label": "Origin of Data",
    "type": "enum"
  },
  "orgntr": {
    "label": "Originator",
    "type": "string"
  },
  "porsty": {
    "label": "Porosity",
    "type": "int"
  },
  "quabch": {
    "label": "Quality of Beach Data",
    "type": "string"
  },
  "datren": {
    "label": "Re-entered Date",
    "type": "string"
  },
  "datres": {
    "label": "Re-suspended Date",
    "type": "string"
  },
  "revebn": {
    "label": "Reverberation",
    "type": "enum"
  },
  "samret": {
    "label": "Sample Retained",
    "type": "string"
  },
  "sbdcov": {
    "label": "Seabed Coverage",
    "type": "int"
  },
  "shpspd": {
    "label": "Ships Speed",
    "type": "float"
  },
  "snrfrq": {
    "label": "Sonar Frequency",
    "type": "enum"
  },
  "snrrsc": {
    "label": "Sonar Range Scale",
    "type": "float"
  },
  "snrflc": {
    "label": "Sonar Reflectivity",
    "type": "enum"
  },
  "sonsig": {
    "label": "Sonar Signal Strength",
    "type": "enum"
  },
  "sndvel": {
    "label": "Sound Velocity",
    "type": "float"
  },
  "soudat": {
    "label": "Sounding Datum",
    "type": "enum"
  },
  "datspd": {
    "label": "Spudded Date",
    "type": "string"
  },
  "stfotn": {
    "label": "Steepest Face Orientation",
    "type": "float"
  },
  "ricsca": {
    "label": "Strength According to Richter Scale",
    "type": "int"
  },
  "magany": {
    "label": "Strength of Magnetic Anomaly",
    "type": "enum"
  },
  "stbacv": {
    "label": "Suitability for ACV Use",
    "type": "enum"
  },
  "srfhgt": {
    "label": "Surf Height",
    "type": "float"
  },
  "srfzne": {
    "label": "Surf Zone",
    "type": "int"
  },
  "surdat": {
    "label": "Survey Date and Time",
    "type": "string"
  },
  "datsus": {
    "label": "Suspension Date",
    "type": "string"
  },
  "swlhgt": {
    "label": "Swell Height",
    "type": "float"
  },
  "tdlrng": {
    "label": "Tidal Range",
    "type": "float"
  },
  "timeyr": {
    "label": "Time of Year",
    "type": "list"
  },
  "tonage": {
    "label": "Tonnage",
    "type": "int"
  },
  "twdbdp": {
    "label": "Towed Body Depth",
    "type": "float"
  },
  "milact": {
    "label": "Type of military activity",
    "type": "list"
  },
  "typton": {
    "label": "Type of Tonnage",
    "type": "enum"
  },
  "typewk": {
    "label": "Type of Wreck",
    "type": "enum"
  },
  "unwrfm": {
    "label": "Underwater Reference Mark",
    "type": "enum"
  },
  "watclr": {
    "label": "Water Clarity",
    "type": "float"
  },
  "wavlen": {
    "label": "Wavelength",
    "type": "float"
  },
  "wbrcap": {
    "label": "Weight Bearing Capability",
    "type": "int"
  },
  "lftwid": {
    "label": "Width (left)",
    "type": "float"
  },
  "rgtwid": {
    "label": "Width (right)",
    "type": "float"
  },
  "hypcat": {
    "label": "Contour Type",
    "type": "enum"
  },
  "souvel": {
    "label": "Sounding Velocity",
    "type": "enum"
  },
  "accres": {
    "label": "Access Restriction",
    "type": "string"
  },
  "apprch": {
    "label": "Approach",
    "type": "string"
  },
  "catbch": {
    "label": "Category of Beach",
    "type": "enum"
  },
  "clperc": {
    "label": "Clearance Percentage",
    "type": "int"
  },
  "commns": {
    "label": "Communications",
    "type": "list"
  },
  "conlev": {
    "label": "Confidence Level",
    "type": "float"
  },
  "extdes": {
    "label": "Exit Description",
    "type": "string"
  },
  "indtry": {
    "label": "Industry",
    "type": "string"
  },
  "lndcon": {
    "label": "Landing Conditions",
    "type": "string"
  },
  "lsract": {
    "label": "Leisure Activity",
    "type": "string"
  },
  "logtcs": {
    "label": "Logistics",
    "type": "list"
  },
  "manvrg": {
    "label": "Manoeuvring",
    "type": "string"
  },
  "mntden": {
    "label": "Mine Threat Density",
    "type": "int"
  },
  "mulcon": {
    "label": "Multiple Contacts",
    "type": "int"
  },
  "navdes": {
    "label": "Navigational Description",
    "type": "string"
  },
  "navdif": {
    "label": "Navigational Difficulty",
    "type": "enum"
  },
  "numrmn": {
    "label": "Number of Remaining Mines",
    "type": "int"
  },
  "pierod": {
    "label": "Pier Contact Details",
    "type": "string"
  },
  "pierdn": {
    "label": "Pier Description",
    "type": "string"
  },
  "prsden": {
    "label": "Prairies Density",
    "type": "int"
  },
  "prbrmn": {
    "label": "Probability for Remaining Mines",
    "type": "float"
  },
  "rmnlmn": {
    "label": "Remaining Mines Likely, Maximum Number",
    "type": "int"
  },
  "sfptna": {
    "label": "Self Protection (Air)",
    "type": "enum"
  },
  "sptnnd": {
    "label": "Self Protection (Near Defence)",
    "type": "enum"
  },
  "sfptns": {
    "label": "Self Protection (Surface)",
    "type": "enum"
  },
  "sencov": {
    "label": "Sensor Coverage",
    "type": "string"
  },
  "sminth": {
    "label": "Simple Initial Threat",
    "type": "float"
  },
  "tgrfwt": {
    "label": "Target Reference Weight",
    "type": "enum"
  },
  "tdltyp": {
    "label": "Tidal Type",
    "type": "enum"
  },
  "typres": {
    "label": "Type of Resource Location",
    "type": "enum"
  },
  "undmnr": {
    "label": "Undetectable Mines Ratio",
    "type": "float"
  },
  "umnrwb": {
    "label": "Undetectable Mines Ratio with Burial",
    "type": "float"
  },
  "umrwob": {
    "label": "Undetectable Mines Ratio without Burial",
    "type": "float"
  },
  "wpncov": {
    "label": "Weapon Coverage",
    "type": "string"
  },
  "onsonr": {
    "label": "On Sonar",
    "type": "enum"
  },
  "hfbmls": {
    "label": "HF Bottom Loss",
    "type": "float"
  },
  "lfbmls": {
    "label": "LF Bottom Loss",
    "type": "float"
  },
  "dtprob": {
    "label": "Detection Probability",
    "type": "float"
  },
  "dsprob": {
    "label": "Disposal Probability",
    "type": "float"
  },
  "clprob": {
    "label": "Classification Probability",
    "type": "float"
  },
  "cswidt": {
    "label": "Characteristic Detection Width (A)",
    "type": "int"
  },
  "csprob": {
    "label": "Characteristic Detection Probability (B)",
    "type": "float"
  },
  "znecol": {
    "label": "Zone Colour",
    "type": "enum"
  },
  "revfqy": {
    "label": "Reverberation Frequency",
    "type": "float"
  },
  "revgan": {
    "label": "Reverberation Grazing Angle",
    "type": "float"
  },
  "secido": {
    "label": "International Defence Organisation (IDO) status",
    "type": "enum"
  },
  "secpmk": {
    "label": "Protective Marking",
    "type": "enum"
  },
  "secown": {
    "label": "Owner Authority",
    "type": "string"
  },
  "seccvt": {
    "label": "Caveat ",
    "type": "string"
  },
  "spcies": {
    "label": "Species",
    "type": "string"
  },
  "swpdat": {
    "label": "Swept date",
    "type": "string"
  },
  "rwylen": {
    "label": "Runway length",
    "type": "int"
  },
  "actper": {
    "label": "Active period",
    "type": "string"
  },
  "maxalt": {
    "label": "Maximum altitude",
    "type": "int"
  },
  "minalt": {
    "label": "Minimum altitude",
    "type": "int"
  },
  "maxftl": {
    "label": "Maximum Flight Level",
    "type": "int"
  },
  "minftl": {
    "label": "Minimum Flight Level",
    "type": "int"
  },
  "bverss": {
    "label": "Bottom Vertical Safety Separation",
    "type": "int"
  },
  "mindep": {
    "label": "Minimum Safe Depth",
    "type": "int"
  },
  "linech": {
    "label": "Interpolated line characteristic",
    "type": "enum"
  },
  "identy": {
    "label": "Identification",
    "type": "string"
  },
  "rclass": {
    "label": "Route Classification",
    "type": "enum"
  },
  "popltn": {
    "label": "Population",
    "type": "int"
  },
  "surtht": {
    "label": "Surface Threat",
    "type": "enum"
  },
  "upbear": {
    "label": "Heading-Up Bearing",
    "type": "float"
  },
  "dnbear": {
    "label": "Heading-Down Bearing",
    "type": "float"
  },
  "icencn": {
    "label": "Ice Concentration",
    "type": "int"
  },
  "dgrhgt": {
    "label": "Danger height",
    "type": "int"
  },
  "depres": {
    "label": "Depth Restriction",
    "type": "string"
  },
  "arecat": {
    "label": "Area Category",
    "type": "enum"
  },
  "exzres": {
    "label": "Existence of Restricted Area",
    "type": "enum"
  },
  "tarstg": {
    "label": "Target Strength",
    "type": "int"
  },
  "quarad": {
    "label": "Qualification of Radar Coverage",
    "type": "int"
  },
  "condet": {
    "label": "Contact Details",
    "type": "string"
  },
  "limanc": {
    "label": "Limit of Anchors and Chains",
    "type": "float"
  },
  "ccmidx": {
    "label": "CCM Index",
    "type": "int"
  },
  "mlclas": {
    "label": "Military Load Classification",
    "type": "enum"
  },
  "mgstyp": {
    "label": "MGS Type",
    "type": "enum"
  },
  "iceact": {
    "label": "Ice Attribute Concentration Total",
    "type": "enum"
  },
  "icesod": {
    "label": "Ice Stage of Development",
    "type": "enum"
  },
  "iceadc": {
    "label": "Ice Advisory Code",
    "type": "string"
  },
  "icebnm": {
    "label": "Number of Icebergs in Area",
    "type": "int"
  },
  "icelnc": {
    "label": "Ice Line Category",
    "type": "enum"
  },
  "icepty": {
    "label": "Ice Polynya Type",
    "type": "enum"
  },
  "icepst": {
    "label": "Ice Polynya Status",
    "type": "enum"
  },
  "icelty": {
    "label": "Ice Lead Type",
    "type": "enum"
  },
  "icelst": {
    "label": "Ice Lead Status",
    "type": "enum"
  },
  "icebsz": {
    "label": "Iceberg Size",
    "type": "enum"
  },
  "icebsh": {
    "label": "Iceberg Shape",
    "type": "enum"
  },
  "icebdr": {
    "label": "Icedrift or Iceberg Direction",
    "type": "enum"
  },
  "icebsp": {
    "label": "Icedrift or Iceberg Speed",
    "type": "float"
  },
  "icemax": {
    "label": "Maximum Ice Thickness",
    "type": "float"
  },
  "icemin": {
    "label": "Minimum Ice Thickness",
    "type": "float"
  },
  "icerdv": {
    "label": "Ice Ridge Development",
    "type": "enum"
  },
  "icelnd": {
    "label": "Land Ice",
    "type": "enum"
  },
  "seadir": {
    "label": "Sea Direction",
    "type": "enum"
  },
  "traden": {
    "label": "Traffic density",
    "type": "string"
  },
  "typshp": {
    "label": "Type of shipping",
    "type": "list"
  },
  "icecvt": {
    "label": "Ice Coverage Type",
    "type": "enum"
  },
  "staobj": {
    "label": "Status of Small Bottom Object",
    "type": "list"
  },
  "icaocd": {
    "label": "ICAO code",
    "type": "string"
  },
  "txtdes": {
    "label": "textual description",
    "type": "string"
  },
  "objtrn": {
    "label": "Object Reference Number",
    "type": "string"
  },
  "objshp": {
    "label": "Object Shape",
    "type": "string"
  },
  "catcnf": {
    "label": "Category of completeness",
    "type": "enum"
  },
  "errell": {
    "label": "Error Ellipse",
    "type": "string"
  },
  "vershf": {
    "label": "Vertical Datum Shift Parameter",
    "type": "float"
  },
  "elvacc": {
    "label": "Absolute Vertical Accuracy",
    "type": "float"
  },
  "reflco": {
    "label": "Reflection Coefficient",
    "type": "float"
  },
  "cpyrit": {
    "label": "Copyright statement",
    "type": "string"
  },
  "updmsg": {
    "label": "Update message",
    "type": "string"
  }
};

/** Enumerated/list attribute values, keyed by attribute acronym → id → meaning. */
export const ENUMS: Record<string, Record<number, string>> =
  {
  "BCNSHP": {
    "1": "stake, pole, perch, post",
    "2": "whity",
    "3": "beacon tower",
    "4": "lattice beacon",
    "5": "pile beacon",
    "6": "cairn",
    "7": "buoyant beacon"
  },
  "BUISHP": {
    "5": "high-rise building",
    "6": "pyramid",
    "7": "cylindrical",
    "8": "spherical",
    "9": "cubic"
  },
  "BOYSHP": {
    "1": "conical (nun, ogival)",
    "2": "can (cylindrical)",
    "3": "spherical",
    "4": "pillar",
    "5": "spar (spindle)",
    "6": "barrel (tun)",
    "7": "super-buoy",
    "8": "ice buoy"
  },
  "CATAIR": {
    "1": "military aeroplane airport",
    "2": "civil aeroplane airport",
    "3": "military heliport",
    "4": "civil heliport",
    "5": "glider airfield",
    "6": "small planes airfield",
    "8": "emergency airfield"
  },
  "CATACH": {
    "1": "unrestricted anchorage",
    "2": "deep water anchorage",
    "3": "tanker anchorage",
    "4": "explosives anchorage",
    "5": "quarantine anchorage",
    "6": "sea-plane anchorage",
    "7": "small craft anchorage",
    "8": "small craft mooring area",
    "9": "anchorage for periods up to 24 hours"
  },
  "CATBRG": {
    "1": "fixed bridge",
    "2": "opening bridge",
    "3": "swing bridge",
    "4": "lifting bridge",
    "5": "bascule bridge",
    "6": "pontoon bridge",
    "7": "draw bridge",
    "8": "transporter bridge",
    "9": "footbridge",
    "10": "viaduct",
    "11": "aqueduct",
    "12": "suspension bridge"
  },
  "CATBUA": {
    "1": "urban area",
    "2": "settlement",
    "3": "village",
    "4": "town",
    "5": "city",
    "6": "holiday village"
  },
  "CATCBL": {
    "1": "power line",
    "3": "transmission line",
    "4": "telephone",
    "5": "telegraph",
    "6": "mooring cable/chain"
  },
  "CATCAN": {
    "1": "transportation",
    "2": "drainage",
    "3": "irrigation"
  },
  "CATCAM": {
    "1": "north cardinal mark",
    "2": "east cardinal mark",
    "3": "south cardinal mark",
    "4": "west cardinal mark"
  },
  "CATCHP": {
    "1": "custom"
  },
  "CATCOA": {
    "1": "steep coast",
    "2": "flat coast",
    "3": "sandy shore",
    "4": "stony shore",
    "5": "shingly shore",
    "6": "glacier (seaward end)",
    "7": "mangrove",
    "8": "marshy shore",
    "9": "coral reef",
    "10": "ice coast"
  },
  "CATCTR": {
    "1": "triangulation point",
    "2": "observation spot",
    "3": "fixed point",
    "4": "bench-mark",
    "5": "boundary mark",
    "6": "horizontal control, main station",
    "7": "horizontal control, secondary station"
  },
  "CATCON": {
    "1": "aerial cableway (telepheric)",
    "2": "belt conveyor"
  },
  "CATCOV": {
    "1": "coverage available",
    "2": "no coverage available"
  },
  "CATCRN": {
    "2": "container crane/gantry",
    "3": "sheerlegs",
    "4": "travelling crane",
    "5": "A-frame"
  },
  "CATDAM": {
    "1": "weir",
    "2": "dam",
    "3": "flood barrage"
  },
  "CATDIS": {
    "1": "distance mark not physically installed",
    "2": "visible mark, pole",
    "3": "visible mark, board",
    "4": "visible mark, unknown shape"
  },
  "CATDOC": {
    "1": "tidal",
    "2": "non-tidal (wet dock)"
  },
  "CATDPG": {
    "2": "chemical waste dumping ground",
    "3": "nuclear waste dumping ground",
    "4": "explosives dumping ground",
    "5": "spoil ground",
    "6": "vessel dumping ground"
  },
  "CATFNC": {
    "1": "fence",
    "3": "hedge",
    "4": "wall"
  },
  "CATFRY": {
    "1": "'free-moving' ferry",
    "2": "cable ferry",
    "3": "ice ferry"
  },
  "CATFIF": {
    "1": "fishing stake",
    "2": "fish trap",
    "3": "fish weir",
    "4": "tunny net"
  },
  "CATFOG": {
    "1": "explosive",
    "2": "diaphone",
    "3": "siren",
    "4": "nautophone",
    "5": "reed",
    "6": "tyfon",
    "7": "bell",
    "8": "whistle",
    "9": "gong",
    "10": "horn"
  },
  "CATFOR": {
    "1": "castle",
    "2": "fort",
    "3": "battery",
    "4": "blockhouse",
    "5": "Martello tower"
  },
  "CATGAT": {
    "2": "flood barrage gate",
    "3": "caisson",
    "4": "lock gate",
    "5": "dyke gate"
  },
  "CATHAF": {
    "1": "RoRo-terminal",
    "3": "ferry terminal",
    "4": "fishing harbour",
    "5": "yacht harbour/marina",
    "6": "naval base",
    "7": "tanker terminal",
    "8": "passenger terminal",
    "9": "shipyard",
    "10": "container terminal",
    "11": "bulk terminal"
  },
  "CATHLK": {
    "1": "floating restaurant",
    "2": "historic ship",
    "3": "museum",
    "4": "accomodation",
    "5": "floating breakwater"
  },
  "CATICE": {
    "1": "fast ice",
    "5": "glacier",
    "8": "polar ice"
  },
  "CATINB": {
    "1": "catenary anchor leg mooring (CALM)",
    "2": "single buoy mooring (SBM or SPM)"
  },
  "CATLND": {
    "1": "fen",
    "2": "marsh",
    "3": "moor/bog",
    "4": "heathland",
    "5": "mountain range",
    "6": "lowlands",
    "7": "canyon lands",
    "8": "paddy field",
    "9": "agricultural land",
    "10": "savanna/grassland",
    "11": "parkland",
    "12": "swamp",
    "13": "landslide",
    "14": "lava flow",
    "15": "salt pan",
    "16": "moraine",
    "17": "crater",
    "18": "cave",
    "19": "rock column or pinnacle"
  },
  "CATLMK": {
    "1": "cairn",
    "2": "cemetery",
    "3": "chimney",
    "4": "dish aerial",
    "5": "flagstaff (flagpole)",
    "6": "flare stack",
    "7": "mast",
    "8": "windsock",
    "9": "monument",
    "10": "column (pillar)",
    "11": "memorial plaque",
    "12": "obelisk",
    "13": "statue",
    "14": "cross",
    "15": "dome",
    "16": "radar scanner",
    "17": "tower",
    "18": "windmill",
    "19": "windmotor",
    "20": "spire/minaret"
  },
  "CATLAM": {
    "1": "port-hand lateral mark",
    "2": "starboard-hand lateral mark",
    "3": "preferred channel to starboard lateral mark",
    "4": "preferred channel to port lateral mark"
  },
  "CATLIT": {
    "1": "directional function",
    "4": "leading light",
    "5": "aero light",
    "6": "air obstruction light",
    "7": "fog detector light",
    "8": "flood light",
    "9": "strip light",
    "10": "subsidiary light",
    "11": "spotlight",
    "12": "front",
    "13": "rear",
    "14": "lower",
    "15": "upper",
    "16": "moir� effect",
    "17": "emergency",
    "18": "bearing light",
    "19": "horizontally disposed",
    "20": "vertically disposed"
  },
  "CATMFA": {
    "1": "crustaceans",
    "2": "oyster/mussels",
    "3": "fish",
    "4": "seaweed"
  },
  "CATMPA": {
    "2": "torpedo exercise area",
    "3": "submarine exercise area",
    "4": "firing danger area",
    "5": "mine-laying practice area",
    "6": "small arms firing range"
  },
  "CATMOR": {
    "1": "dolphin",
    "2": "deviation dolphin",
    "3": "bollard",
    "4": "tie-up wall",
    "5": "post or pile",
    "6": "chain/wire/cable",
    "7": "mooring buoy"
  },
  "CATNAV": {
    "1": "clearing line",
    "2": "transit line",
    "3": "leading line bearing a recommended track"
  },
  "CATOBS": {
    "1": "snag / stump",
    "2": "wellhead",
    "3": "diffuser",
    "4": "crib",
    "5": "fish haven",
    "6": "foul area",
    "7": "foul ground",
    "8": "ice boom",
    "9": "ground tackle"
  },
  "CATOFP": {
    "1": "oil derrick / rig",
    "2": "production platform",
    "3": "observation / research platform",
    "4": "articulated loading platform (ALP)",
    "5": "single anchor leg mooring (SALM)",
    "6": "mooring tower",
    "7": "artificial island",
    "8": "floating production, storage and off-loading vessel (FPSO)",
    "9": "accomodation platform",
    "10": "navigation, communication and control buoy (NCCB)"
  },
  "CATOLB": {
    "1": "oil retention (high pressure pipe)",
    "2": "floating oil barrier"
  },
  "CATPLE": {
    "1": "stake",
    "3": "post",
    "4": "tripodal"
  },
  "CATPIL": {
    "1": "boarding by pilot-cruising vessel",
    "2": "boarding by helicopter",
    "3": "pilot comes out from shore"
  },
  "CATPIP": {
    "2": "outfall pipe",
    "3": "intake pipe",
    "4": "sewer",
    "5": "bubbler system",
    "6": "supply pipe"
  },
  "CATPRA": {
    "1": "quarry",
    "2": "mine",
    "3": "stockpile",
    "4": "power station area",
    "5": "refinery area",
    "6": "timber yard",
    "7": "factory area",
    "8": "tank farm",
    "9": "wind farm"
  },
  "CATPYL": {
    "1": "power transmission pylon/pole",
    "2": "telephone/telegraph pylon/pole",
    "3": "aerial cableway/sky pylon",
    "4": "bridge pylon/tower",
    "5": "bridge pier"
  },
  "CATQUA": {
    "1": "data quality A",
    "2": "data quality B",
    "3": "data quality C",
    "4": "data quality D",
    "5": "data quality E",
    "6": "quality not evaluated"
  },
  "CATRAS": {
    "1": "radar surveillance station",
    "2": "coast radar station"
  },
  "CATRTB": {
    "1": "ramark, radar beacon transmitting continuously",
    "2": "racon, radar transponder beacon",
    "3": "leading racon/radar transponder beacon"
  },
  "CATROS": {
    "1": "circular (non-directional) marine or aero-marine radiobeacon",
    "2": "directional radiobeacon",
    "3": "rotating-pattern radiobeacon",
    "4": "Consol beacon",
    "5": "radio direction-finding station",
    "6": "coast radio station providing QTG service",
    "7": "aeronautical radiobeacon",
    "8": "Decca",
    "9": "Loran C",
    "10": "Differential GPS",
    "11": "Toran",
    "12": "Omega",
    "13": "Syledis",
    "14": "Chaika (Chayka)"
  },
  "CATTRK": {
    "1": "based on a system of fixed marks",
    "2": "not based on a system of fixed marks"
  },
  "CATRSC": {
    "1": "rescue station with lifeboat",
    "2": "rescue station with rocket",
    "4": "refuge for shipwrecked mariners",
    "5": "refuge for intertidal area walkers",
    "6": "lifeboat lying at a mooring"
  },
  "CATREA": {
    "1": "offshore safety zone",
    "4": "nature reserve",
    "5": "bird sanctuary",
    "6": "game preserve",
    "7": "seal sanctuary",
    "8": "degaussing range",
    "9": "military area",
    "10": "historic wreck area",
    "12": "navigational aid safety zone",
    "14": "minefield",
    "18": "swimming area",
    "19": "waiting area",
    "20": "research area",
    "21": "dredging area",
    "22": "fish sanctuary",
    "23": "ecological reserve",
    "24": "no wake area",
    "25": "swinging area"
  },
  "CATROD": {
    "1": "motorway",
    "2": "major road",
    "3": "minor road",
    "4": "track / path",
    "5": "major street",
    "6": "minor street",
    "7": "crossing"
  },
  "CATRUN": {
    "1": "aeroplane",
    "2": "helicopter landing pad"
  },
  "CATSEA": {
    "2": "gat",
    "3": "bank",
    "4": "deep",
    "5": "bay",
    "6": "trench",
    "7": "basin",
    "8": "mud flats",
    "9": "reef",
    "10": "ledge",
    "11": "canyon",
    "12": "narrows",
    "13": "shoal",
    "14": "knoll",
    "15": "ridge",
    "16": "seamount",
    "17": "pinnacle",
    "18": "abyssal plain",
    "19": "plateau",
    "20": "spur",
    "21": "shelf",
    "22": "trough",
    "23": "saddle",
    "24": "abyssal hills",
    "25": "apron",
    "26": "archipelagic apron",
    "27": "borderland",
    "28": "continental margin",
    "29": "continental rise",
    "30": "escarpment",
    "31": "fan",
    "32": "fracture zone",
    "33": "gap",
    "34": "guyot",
    "35": "hill",
    "36": "hole",
    "37": "levee",
    "38": "median valley",
    "39": "moat",
    "40": "mountains",
    "41": "peak",
    "42": "province",
    "43": "rise",
    "44": "seachannel",
    "45": "seamount chain",
    "46": "shelf edge",
    "47": "sill",
    "48": "slope",
    "49": "terrace",
    "50": "valley",
    "51": "canal",
    "52": "lake",
    "53": "river"
  },
  "CATSLC": {
    "1": "breakwater",
    "2": "groyne (groin)",
    "3": "mole",
    "4": "pier ( jetty)",
    "5": "promenadepier",
    "6": "wharf (quay)",
    "7": "training wall",
    "8": "rip rap",
    "9": "revetment",
    "10": "sea wall",
    "11": "landing steps",
    "12": "ramp",
    "13": "slipway",
    "14": "fender",
    "15": "solid face wharf",
    "16": "open face wharf"
  },
  "CATSIT": {
    "1": "port control",
    "2": "port entry and departure",
    "3": "International Port Traffic",
    "4": "berthing",
    "5": "dock",
    "6": "lock",
    "7": "flood barrage",
    "8": "bridge passage",
    "9": "dredging"
  },
  "CATSIW": {
    "1": "danger",
    "2": "maritime obstruction",
    "3": "cable",
    "4": "military practice",
    "5": "distress",
    "6": "weather",
    "7": "storm",
    "8": "ice",
    "9": "time",
    "10": "tide",
    "11": "tidal stream",
    "12": "tide gauge",
    "13": "tide scale",
    "14": "diving"
  },
  "CATSIL": {
    "1": "silo in general",
    "2": "tank in general",
    "3": "grain elevator",
    "4": "water tower"
  },
  "CATSLO": {
    "1": "cutting",
    "2": "embankment",
    "3": "dune",
    "4": "hill",
    "5": "pingo",
    "6": "cliff",
    "7": "scree"
  },
  "CATSCF": {
    "1": "visitor`s berth",
    "2": "nautical club",
    "3": "boat hoist",
    "4": "sailmaker",
    "5": "boatyard",
    "6": "public inn",
    "7": "restaurant",
    "8": "chandler",
    "9": "provisions",
    "10": "doctor",
    "11": "pharmacy",
    "12": "water tap",
    "13": "fuel station",
    "14": "electricity",
    "15": "bottle gas",
    "16": "showers",
    "17": "launderette",
    "18": "public toilets",
    "19": "post box",
    "20": "public telephone",
    "21": "refuse bin",
    "22": "car park",
    "23": "parking for boats and trailers",
    "24": "caravan site",
    "25": "camping site",
    "26": "sewerage pump-out station",
    "27": "emergency telephone",
    "28": "landing / launching place for boats",
    "29": "visitors mooring",
    "30": "scrubbing berth",
    "31": "picnic area"
  },
  "CATSPM": {
    "1": "firing danger area mark",
    "2": "target mark",
    "3": "marker ship mark",
    "4": "degaussing range mark",
    "5": "barge mark",
    "6": "cable mark",
    "7": "spoil ground mark",
    "8": "outfall mark",
    "9": "ODAS (Ocean-Data-Acquisition-System)",
    "10": "recording mark",
    "11": "seaplane anchorage mark",
    "12": "recreation zone mark",
    "13": "private mark",
    "14": "mooring mark",
    "15": "LANBY (Large Automatic Navigational Buoy)",
    "16": "leading mark",
    "17": "measured distance mark",
    "18": "notice mark",
    "19": "TSS mark (Traffic Separation Scheme)",
    "20": "anchoring prohibited mark",
    "21": "berthing prohibited mark",
    "22": "overtaking prohibited mark",
    "23": "two-way traffic prohibited mark",
    "24": "'reduced wake' mark",
    "25": "speed limit mark",
    "26": "stop mark",
    "27": "general warning mark",
    "28": "'sound ship's siren' mark",
    "29": "restricted vertical clearence mark",
    "30": "maximum vessel's draught mark",
    "31": "restricted horizontal clearance mark",
    "32": "strong current warning mark",
    "33": "berthing permitted mark",
    "34": "overhead power cable mark",
    "35": "'channel edge gradient' mark",
    "36": "telephone mark",
    "37": "ferry crossing mark",
    "39": "pipline mark",
    "40": "anchorage mark",
    "41": "clearing mark",
    "42": "control mark",
    "43": "diving mark",
    "44": "refuge beacon",
    "45": "foul ground mark",
    "46": "yachting mark",
    "47": "heliport mark",
    "48": "GPS mark",
    "49": "seaplane landing mark",
    "50": "entry prohibited mark",
    "51": "work in progress mark",
    "52": "mark with unknown purpose"
  },
  "CATTSS": {
    "1": "IMO - adopted",
    "2": "not IMO - adopted"
  },
  "CATVEG": {
    "1": "grassland",
    "3": "bush",
    "4": "deciduous wood",
    "5": "coniferous  wood",
    "6": "wood in general (inc mixed wood)",
    "7": "mangroves",
    "10": "mixed crops",
    "11": "reed",
    "12": "moos",
    "13": "tree in general",
    "14": "evergreen tree",
    "15": "coniferous tree",
    "16": "palm tree",
    "17": "nipa palm tree",
    "18": "casuarina tree",
    "19": "eucalypt tree",
    "20": "deciduous tree",
    "21": "mangrove tree",
    "22": "filao tree"
  },
  "CATWAT": {
    "1": "breakers",
    "2": "eddies",
    "3": "overfalls",
    "4": "tide rips",
    "5": "bombora"
  },
  "CATWED": {
    "1": "kelp",
    "2": "sea weed",
    "3": "sea grass",
    "4": "saragasso"
  },
  "CATWRK": {
    "1": "non-dangerous wreck",
    "2": "dangerous wreck",
    "3": "distributed remains of wreck",
    "4": "wreck showing mast/masts",
    "5": "wreck showing any portion of hull or superstructure"
  },
  "CATZOC": {
    "1": "zone of confidence A1",
    "2": "zone of confidence A2",
    "3": "zone of confidence B",
    "4": "zone of confidence C",
    "5": "zone of confidence D",
    "6": "zone of confidence U (data not assessed)"
  },
  "$SPACE": {
    "1": "expanded/condensed",
    "2": "standard"
  },
  "COLOUR": {
    "1": "white",
    "2": "black",
    "3": "red",
    "4": "green",
    "5": "blue",
    "6": "yellow",
    "7": "grey",
    "8": "brown",
    "9": "amber",
    "10": "violet",
    "11": "orange",
    "12": "magenta",
    "13": "pink"
  },
  "COLPAT": {
    "1": "horizontal stripes",
    "2": "vertical stripes",
    "3": "diagonal stripes",
    "4": "squared",
    "5": "stripes (direction unknown)",
    "6": "border stripes"
  },
  "CONDTN": {
    "1": "under construction",
    "2": "ruined",
    "3": "under reclamation",
    "4": "wingless",
    "5": "planned construction"
  },
  "CONRAD": {
    "1": "radar conspicuous",
    "2": "not radar conspicuous",
    "3": "radar conspicuous (has radar reflector)"
  },
  "CONVIS": {
    "1": "visual conspicuous",
    "2": "not visual conspicuous"
  },
  "DUNITS": {
    "1": "metres",
    "2": "fathoms and feet",
    "3": "feet",
    "4": "fathoms and fractions"
  },
  "EXCLIT": {
    "1": "light shown without change of character",
    "2": "daytime light",
    "3": "fog light",
    "4": "night light"
  },
  "EXPSOU": {
    "1": "within the range of depth of the surrounding depth area",
    "2": "shoaler than range of depth of the surrounding depth area",
    "3": "deeper than range of depth of the surrounding depth area"
  },
  "FUNCTN": {
    "2": "harbour-master's office",
    "3": "custom office",
    "4": "health office",
    "5": "hospital",
    "6": "post office",
    "7": "hotel",
    "8": "railway station",
    "9": "police station",
    "10": "water-police station",
    "11": "pilot office",
    "12": "pilot lookout",
    "13": "bank office",
    "14": "headquarters for district control",
    "15": "transit shed/warehouse",
    "16": "factory",
    "17": "power station",
    "18": "administrative",
    "19": "educational facility",
    "20": "church",
    "21": "chapel",
    "22": "temple",
    "23": "pagoda",
    "24": "shinto shrine",
    "25": "buddhist temple",
    "26": "mosque",
    "27": "marabout",
    "28": "lookout",
    "29": "communication",
    "30": "television",
    "31": "radio",
    "32": "radar",
    "33": "light support",
    "34": "microwave",
    "35": "cooling",
    "36": "observation",
    "37": "timeball",
    "38": "clock",
    "39": "control",
    "40": "airship mooring",
    "41": "stadium",
    "42": "bus station"
  },
  "HUNITS": {
    "1": "metres",
    "2": "feet"
  },
  "JRSDTN": {
    "1": "international",
    "2": "national",
    "3": "national sub-division"
  },
  "$JUSTH": {
    "1": "centre justified",
    "2": "right justified",
    "3": "left justified"
  },
  "$JUSTV": {
    "1": "bottom justified",
    "2": "centre justified",
    "3": "top justified"
  },
  "LITCHR": {
    "1": "fixed",
    "2": "flashing",
    "3": "long-flashing",
    "4": "quick-flashing",
    "5": "very quick-flashing",
    "6": "ultra quick-flashing",
    "7": "isophased",
    "8": "occulting",
    "9": "interrupted quick-flashing",
    "10": "interrupted very quick-flashing",
    "11": "interrupted ultra quick-flashing",
    "12": "morse",
    "13": "fixed / flash",
    "14": "flash / long-flash",
    "15": "occulting / flash",
    "16": "fixed / long-flash",
    "17": "occulting alternating",
    "18": "long-flash alternating",
    "19": "flash alternating",
    "20": "group alternating",
    "25": "quick-flash plus long-flash",
    "26": "very quick-flash plus long-flash",
    "27": "ultra quick-flash plus long-flash",
    "28": "alternating",
    "29": "fixed and alternating flashing"
  },
  "LITVIS": {
    "1": "high intensity",
    "2": "low intensity",
    "3": "faint",
    "4": "intensified",
    "5": "unintensified",
    "6": "visibility deliberately restricted",
    "7": "obscured",
    "8": "partially obscured"
  },
  "MARSYS": {
    "1": "IALA A",
    "2": "IALA B",
    "9": "no system",
    "10": "other sytem"
  },
  "NATCON": {
    "1": "masonry",
    "2": "concreted",
    "3": "loose boulders",
    "4": "hard surfaced",
    "5": "unsurfaced",
    "6": "wooden",
    "7": "metal",
    "8": "glass reinforced plastic (GRP)",
    "9": "painted"
  },
  "NATSUR": {
    "1": "mud",
    "2": "clay",
    "3": "silt",
    "4": "sand",
    "5": "stone",
    "6": "gravel",
    "7": "pebbles",
    "8": "cobbles",
    "9": "rock",
    "11": "lava",
    "14": "coral",
    "17": "shells",
    "18": "boulder"
  },
  "NATQUA": {
    "1": "fine",
    "2": "medium",
    "3": "coarse",
    "4": "broken",
    "5": "sticky",
    "6": "soft",
    "7": "stiff",
    "8": "volcanic",
    "9": "calcareous",
    "10": "hard"
  },
  "PRODCT": {
    "1": "oil",
    "2": "gas",
    "3": "water",
    "4": "stone",
    "5": "coal",
    "6": "ore",
    "7": "chemicals",
    "8": "drinking water",
    "9": "milk",
    "10": "bauxite",
    "11": "coke",
    "12": "iron ingots",
    "13": "salt",
    "14": "sand",
    "15": "timber",
    "16": "sawdust / wood chips",
    "17": "scrap metal",
    "18": "liquified natural gas (LNG)",
    "19": "liquified petroleum gas (LPG)",
    "20": "wine",
    "21": "cement",
    "22": "grain"
  },
  "QUASOU": {
    "1": "depth known",
    "2": "depth unknown",
    "3": "doubtful sounding",
    "4": "unreliable sounding",
    "5": "no bottom found at value shown",
    "6": "least depth known",
    "7": "least depth unknown, safe clearance at value shown",
    "8": "value reported (not surveyed)",
    "9": "value reported (not confirmed)",
    "10": "maintained depth",
    "11": "not reguraly maintained"
  },
  "RESTRN": {
    "1": "anchoring prohibited",
    "2": "anchoring restricted",
    "3": "fishing prohibited",
    "4": "fishing restricted",
    "5": "trawling prohibited",
    "6": "trawling restricted",
    "7": "entry prohibited",
    "8": "entry restricted",
    "9": "dredging prohibited",
    "10": "dredging restricted",
    "11": "diving prohibited",
    "12": "diving restricted",
    "13": "no wake",
    "14": "area to be avoided",
    "15": "construction prohibited"
  },
  "SIGGEN": {
    "1": "automatically",
    "2": "by wave action",
    "3": "by hand",
    "4": "by wind"
  },
  "STATUS": {
    "1": "permanent",
    "2": "occasional",
    "3": "recommended",
    "4": "disused",
    "5": "periodically/intermittent",
    "6": "reserved",
    "7": "temporary",
    "8": "private",
    "9": "mandatory",
    "11": "extinguished",
    "12": "illuminated",
    "13": "historic",
    "14": "public",
    "15": "synchronized",
    "16": "watched",
    "17": "un-watched",
    "18": "existence doubtful"
  },
  "SURTYP": {
    "1": "reconnaissance/sketch survey",
    "2": "controlled survey",
    "4": "examintion survey",
    "5": "passage survey",
    "6": "remotely sensed"
  },
  "TECSOU": {
    "1": "found by echo-sounder",
    "2": "found by side scan sonar",
    "3": "found by multi-beam",
    "4": "found by diver",
    "5": "found by lead-line",
    "6": "swept by wire-drag",
    "7": "found by laser",
    "8": "swept by vertical acoustic system",
    "9": "found by electromagnetic sensor",
    "10": "photogrammetry",
    "11": "satelite imagery",
    "12": "found by levelling",
    "13": "swept by side-scan sonar",
    "14": "computer generated"
  },
  "T_ACWL": {
    "1": "better than 0.1m and 10 minutes",
    "2": "worse than 0.1m or 10 minutes"
  },
  "T_MTOD": {
    "1": "simplified harmonic method of tidal prediction",
    "2": "full harmonic method of tidal prediction",
    "3": "height and time difference non-harmonic method"
  },
  "$TINTS": {
    "1": "darkest blue",
    "2": "medium blue",
    "3": "lightest blue"
  },
  "TOPSHP": {
    "1": "cone, point up",
    "2": "cone, point down",
    "3": "sphere",
    "4": "2 sphere",
    "5": "cylinder (can)",
    "6": "board",
    "7": "x-shape (St. Andrew's cross)",
    "8": "upright cross (St. George cross)",
    "9": "cube, point up",
    "10": "2 cones, point to point",
    "11": "2 cones, base to base",
    "12": "rhombus (diamond)",
    "13": "2 cones (points upward)",
    "14": "2 cones (points downward)",
    "15": "besom, point up (broom or perch)",
    "16": "besom, point down (broom or perch)",
    "17": "flag",
    "18": "sphere over rhombus",
    "19": "square",
    "20": "rectangle, horizontal",
    "21": "rectangle, vertical",
    "22": "trapezium, up",
    "23": "trapezium, down",
    "24": "triangle, point up",
    "25": "triangle, point down",
    "26": "circle",
    "27": "two upright crosses (one over the other)",
    "28": "T-shape",
    "29": "triangle pointing up over a circle",
    "30": "upright cross over a circle",
    "31": "rhombus over a circle",
    "32": "circle over a triangle pointing up",
    "33": "other shape (see INFORM)"
  },
  "TRAFIC": {
    "1": "inbound",
    "2": "outbound",
    "3": "one-way",
    "4": "two-way"
  },
  "VERDAT": {
    "1": "Mean low water springs",
    "2": "Mean lower low water springs",
    "3": "Mean sea level",
    "4": "Lowest low water",
    "5": "Mean low water",
    "6": "Lowest low water springs",
    "7": "Approximate mean low water springs",
    "8": "Indian spring low water",
    "9": "Low water springs",
    "10": "Approximate lowest astronomical tide",
    "11": "Nearly lowest low water",
    "12": "Mean lower low water",
    "13": "Low water",
    "14": "Approximate mean low water",
    "15": "Approximate mean lower low water",
    "16": "Mean high water",
    "17": "Mean high water springs",
    "18": "High water",
    "19": "Approximate mean sea level",
    "20": "High water springs",
    "21": "Mean higher high water",
    "22": "Equinoctial spring low water",
    "23": "Lowest astronomical tide",
    "24": "Local datum",
    "25": "International Great Lakes Datum 1985",
    "26": "Mean water level",
    "27": "Lower low water large tide",
    "28": "Higher high water lage tide",
    "29": "Nearly highest high water"
  },
  "WATLEV": {
    "1": "partly submerged at high water",
    "2": "always dry",
    "3": "always under water/submerged",
    "4": "covers and uncovers",
    "5": "awash",
    "6": "subject to inundation or flooding"
  },
  "HORDAT": {
    "1": "WGS 72",
    "2": "WGS 84",
    "3": "European 1950",
    "4": "Potsdam Datum",
    "5": "Adindan",
    "6": "Afgooye",
    "7": "Ain el Abd 1970",
    "8": "Anna 1 Astro 1965",
    "9": "Antigua Island Astro 1943",
    "10": "Arc 1950",
    "11": "Arc 1960",
    "12": "Ascension Island 1958",
    "13": "Astro beacon \\E\\ 1945",
    "14": "Astro DOS 71/4",
    "15": "Astro Tern Island (FRIG) 1961",
    "16": "Astronimical Station 1952",
    "17": "Australian Geodetic 1966",
    "18": "Australian Geodetic 1984",
    "19": "Ayabelle Lighthouse",
    "20": "Bellevue (IGN)",
    "21": "Bermuda 1957",
    "22": "Bissau",
    "23": "Bogota Observatory",
    "24": "Bukit Rimpah",
    "25": "Camp Area Astro",
    "26": "Campo Inchauspe 1969",
    "27": "Canton Astro 1966",
    "28": "Cape",
    "29": "Cape Canaveral",
    "30": "Carthage",
    "31": "Chatam Island Astro 1971",
    "32": "Chua Astro",
    "33": "Corrego Alegre",
    "34": "Dabola",
    "35": "Djakarta (Batavia)",
    "36": "DOS 1968",
    "37": "Easter Island 1967",
    "38": "European 1979",
    "39": "Fort Thomas 1955",
    "40": "Gan 1970",
    "41": "Geodetic Datum 1949",
    "42": "Graciosa Base SW 1948",
    "43": "Guam 1963",
    "44": "Ganung Segara",
    "45": "GUX 1 Astro",
    "46": "Herat North",
    "47": "Hjorsey 1955",
    "48": "Hong Kong 1963",
    "49": "Hu-Tzu-Shan",
    "50": "Indian",
    "51": "Indian 1954",
    "52": "Indian 1975",
    "53": "Ireland 1965",
    "54": "ISTS 061 Astro 1968",
    "55": "ISTS 073 Astro 1969",
    "56": "Johnston Island 1961",
    "57": "Kandawala",
    "58": "Kerguelen Island 1949",
    "59": "Kertau 1948",
    "60": "Kusaie Astro 1951",
    "61": "",
    "62": "",
    "63": "",
    "64": "",
    "65": "",
    "66": "",
    "67": "",
    "68": "",
    "69": "",
    "70": "",
    "71": "",
    "72": "",
    "73": "",
    "74": "",
    "75": "",
    "76": "",
    "77": "",
    "78": "",
    "79": "",
    "80": "",
    "81": "",
    "82": "",
    "83": "",
    "84": "",
    "85": "",
    "86": "",
    "87": "",
    "88": "",
    "89": "",
    "90": "",
    "91": "",
    "92": "",
    "93": "",
    "94": "",
    "95": "",
    "96": "",
    "97": "",
    "98": "",
    "99": "South Asia",
    "100": "Tananarive Observatory 1925"
  },
  "QUAPOS": {
    "1": "surveyed",
    "2": "unsurveyed",
    "3": "inadequately surveyed",
    "4": "approximated",
    "5": "position doubtful",
    "6": "unreliable",
    "7": "reported (not surveyed)",
    "8": "reported (not confirmed)",
    "9": "estimated",
    "10": "precisely known",
    "11": "calculated"
  }
};
