#!/usr/bin/env node
/**
 * Generates `src/charts/s57/catalogue.generated.ts` from the vendored GDAL
 * S-57 CSVs (the IHO S-57 Appendix A Object Catalogue). Run after updating the
 * CSVs:
 *
 *   npm run gen:s57
 *
 * Inputs (vendored in src/charts/s57/, alongside the generated output):
 *   - s57objectclasses.csv  → OBJL code → { acronym, label }
 *   - s57attributes.csv     → attribute acronym → { label, type }
 *   - s57expectedinput.csv  → enumerated (attrCode, id) → meaning
 *
 * The app-specific concerns (which attributes to hide, depth/light formatting,
 * significance) live in objects.ts / attributes.ts on top of this data.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const s57Dir = join(here, "../src/charts/s57");
const out = join(s57Dir, "catalogue.generated.ts");

/** Minimal RFC-4180 CSV parser: handles quoted fields, escaped quotes ("")
 *  and commas/newlines inside quotes. Returns an array of string-cell rows. */
function parseCsv(text) {
  const rows = [];
  let row = [];
  let cell = "";
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          cell += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        cell += c;
      }
    } else if (c === '"') {
      inQuotes = true;
    } else if (c === ",") {
      row.push(cell);
      cell = "";
    } else if (c === "\n" || c === "\r") {
      if (c === "\r" && text[i + 1] === "\n") i++;
      row.push(cell);
      rows.push(row);
      row = [];
      cell = "";
    } else {
      cell += c;
    }
  }
  if (cell !== "" || row.length) {
    row.push(cell);
    rows.push(row);
  }
  return rows.filter((r) => r.length > 1 || (r.length === 1 && r[0] !== ""));
}

function read(name) {
  const rows = parseCsv(readFileSync(join(s57Dir, name), "utf8"));
  const header = rows[0];
  return rows.slice(1).map((r) => Object.fromEntries(header.map((h, i) => [h, r[i] ?? ""])));
}

// S-57 attribute type letter → semantic type we care about.
//   E enumerated · L list (multiple enums) · F float · I integer · A coded · S free
const TYPE = { E: "enum", L: "list", F: "float", I: "int", A: "string", S: "string" };

const objectClasses = {};
for (const r of read("s57objectclasses.csv")) {
  const code = Number(r.Code);
  if (!Number.isFinite(code) || !r.Acronym) continue;
  objectClasses[code] = { acronym: r.Acronym, label: r.ObjectClass };
}

const attributes = {}; // acronym → { code, label, type }
const codeToAcronym = {}; // attr code → acronym (to key enums by acronym)
for (const r of read("s57attributes.csv")) {
  const code = Number(r.Code);
  if (!Number.isFinite(code) || !r.Acronym) continue;
  attributes[r.Acronym] = { label: r.Attribute, type: TYPE[r.Attributetype] ?? "string" };
  codeToAcronym[code] = r.Acronym;
}

const enums = {}; // acronym → { id → meaning }
for (const r of read("s57expectedinput.csv")) {
  const acronym = codeToAcronym[Number(r.Code)];
  const id = Number(r.ID);
  if (!acronym || !Number.isFinite(id)) continue;
  (enums[acronym] ??= {})[id] = r.Meaning;
}

const banner = `// GENERATED by scripts/generate-s57.mjs — DO NOT EDIT.
// Source: IHO S-57 Appendix A Object Catalogue (vendored GDAL CSVs).
// Regenerate with: npm run gen:s57
`;

const body = `${banner}
/** An S-57 attribute's value domain. \`enum\`/\`list\` map through ENUMS. */
export type AttributeType = "enum" | "list" | "float" | "int" | "string";

/** OBJL (object-class code) → acronym + official label. */
export const OBJECT_CLASSES: Record<number, { acronym: string; label: string }> =
  ${JSON.stringify(objectClasses, null, 2)};

/** Attribute acronym (e.g. "DRVAL1", "WATLEV") → official label + value type. */
export const ATTRIBUTES: Record<string, { label: string; type: AttributeType }> =
  ${JSON.stringify(attributes, null, 2)};

/** Enumerated/list attribute values, keyed by attribute acronym → id → meaning. */
export const ENUMS: Record<string, Record<number, string>> =
  ${JSON.stringify(enums, null, 2)};
`;

writeFileSync(out, body);
console.log(
  `Wrote ${out}\n  ${Object.keys(objectClasses).length} object classes, ` +
    `${Object.keys(attributes).length} attributes, ` +
    `${Object.keys(enums).length} enumerated attributes`,
);
